In [ ]:
# Understand dataset

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')
import seaborn as sns
import numpy as np
import json
import warnings
warnings.filterwarnings('ignore')
import base64
import io
from imageio import imread
import codecs
from IPython.display import HTML
import re

In [2]:
movies = pd.read_csv('tmdb_5000_movies.csv')

In [13]:
mov = pd.read_csv('tmdb_5000_credits.csv')

In [3]:
# 第一个文件Json格式数据提取

In [4]:
movies['genres']=movies['genres'].apply(json.loads)
for index,i in zip(movies.index,movies['genres']):
    list1=[]
    for j in range(len(i)):
        list1.append((i[j]['name']))
    movies.loc[index,'genres']=str(list1)

movies['keywords']=movies['keywords'].apply(json.loads)
for index,i in zip(movies.index,movies['keywords']):
    list1=[]
    for j in range(len(i)):
        list1.append((i[j]['name']))
    movies.loc[index,'keywords']=str(list1)

# movies['production_companies']=movies['production_companies'].apply(json.loads)
# for index,i in zip(movies.index,movies['production_companies']):
#     list1=[]
#     for j in range(len(i)):
#         list1.append((i[j]['id']))
#     movies.loc[index,'production_companies']=str(list1)
      
movies['production_countries']=movies['production_countries'].apply(json.loads)
for index,i in zip(movies.index,movies['production_countries']):
    list1=[]
    for j in range(len(i)):
        list1.append((i[j]['iso_3166_1']))
    movies.loc[index,'production_countries']=str(list1)

In [5]:
movies['production_companies']=movies['production_companies'].apply(json.loads)
def production_company(x):
    list1 = []
    for i in x:
        if(i['id'] not in list1):
            list1.append(i['id'])
    return list1
movies['production_companies']=movies['production_companies'].apply(production_company)

In [6]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"['Action', 'Adventure', 'Fantasy', 'Science Fi...",http://www.avatarmovie.com/,19995,"['culture clash', 'future', 'space war', 'spac...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[289, 306, 444, 574]","['US', 'GB']",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"['Adventure', 'Fantasy', 'Action']",http://disney.go.com/disneypictures/pirates/,285,"['ocean', 'drug abuse', 'exotic island', 'east...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[2, 130, 19936]",['US'],2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"['Action', 'Adventure', 'Crime']",http://www.sonypictures.com/movies/spectre/,206647,"['spy', 'based on novel', 'secret agent', 'seq...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[5, 10761, 69434]","['GB', 'US']",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"['Action', 'Crime', 'Drama', 'Thriller']",http://www.thedarkknightrises.com/,49026,"['dc comics', 'crime fighter', 'terrorist', 's...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[923, 6194, 9993, 9996]",['US'],2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"['Action', 'Adventure', 'Science Fiction']",http://movies.disney.com/john-carter,49529,"['based on novel', 'mars', 'medallion', 'space...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,[2],['US'],2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [7]:
# 把字符串转成list

In [8]:
movies['genres']=movies['genres'].str.strip('[]').str.strip().str.replace("'",'')
movies['genres']=movies['genres'].str.split(', ')
movies['keywords'] = movies['keywords'].str.strip('[]').str.strip().str.replace("'",'')
movies['keywords']=movies['keywords'].str.split(', ')
# movies['production_companies']=movies['production_companies'].str.strip('[]').str.strip().str.replace("'",'')
# movies['production_companies']=movies['production_companies'].str.split(', ')
movies['production_countries']=movies['production_countries'].str.strip('[]').str.strip().str.replace("'",'')
movies['production_countries']=movies['production_countries'].str.split(', ')

In [9]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[Action, Adventure, Fantasy, Science Fiction]",http://www.avatarmovie.com/,19995,"[culture clash, future, space war, space colon...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[289, 306, 444, 574]","[US, GB]",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[Adventure, Fantasy, Action]",http://disney.go.com/disneypictures/pirates/,285,"[ocean, drug abuse, exotic island, east india ...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[2, 130, 19936]",[US],2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[Action, Adventure, Crime]",http://www.sonypictures.com/movies/spectre/,206647,"[spy, based on novel, secret agent, sequel, mi...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[5, 10761, 69434]","[GB, US]",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[Action, Crime, Drama, Thriller]",http://www.thedarkknightrises.com/,49026,"[dc comics, crime fighter, terrorist, secret i...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[923, 6194, 9993, 9996]",[US],2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[Action, Adventure, Science Fiction]",http://movies.disney.com/john-carter,49529,"[based on novel, mars, medallion, space travel...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,[2],[US],2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [10]:
# 处理第二个文件

In [14]:
mov['cast']=mov['cast'].apply(json.loads)
def main_cast(x):
    cnt = 0
    list1 = []
    #只保留主演演员
    for i in x:
        if len(list1)<=10:
            if(i['id'] not in list1):
                list1.append(i['id'])
        else:
            return list1
    return list1
mov['main_cast']=mov['cast'].apply(main_cast)

In [17]:
mov.head()

,movie_id,title,cast,crew,main_cast
0,19995,Avatar,"[{'cast_id': 242, 'character': 'Jake Sully', '...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...","[65731, 8691, 10205, 32747, 17647, 1771, 59231..."
1,285,Pirates of the Caribbean: At World's End,"[{'cast_id': 4, 'character': 'Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...","[85, 114, 116, 1640, 1619, 2440, 118, 1709, 24..."
2,206647,Spectre,"[{'cast_id': 1, 'character': 'James Bond', 'cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...","[8784, 27319, 121529, 5469, 28782, 17064, 2038..."
3,49026,The Dark Knight Rises,"[{'cast_id': 2, 'character': 'Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...","[3894, 3895, 64, 1813, 2524, 8293, 24045, 192,..."
4,49529,John Carter,"[{'cast_id': 5, 'character': 'John Carter', 'c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...","[60900, 21044, 2206, 5293, 19159, 2983, 8785, ..."

In [18]:
mov['crew']=mov['crew'].apply(json.loads)
#Crew部分除了director都按department分类
# director
def director(x):
    list1 = []
    for i in x:
        if i['job'] == 'Director':
            if(i['id'] not in list1):
                list1.append(i['id'])
    return list1
mov['director']=mov['crew'].apply(director)

In [19]:
def editing(x):
    list1 = []
    for i in x:
        if i['department'] == 'Editing':
            if(i['id'] not in list1):
                list1.append(i['id'])
    return list1
mov['editing']=mov['crew'].apply(editing)

In [20]:
def sound(x):
    list1 = []
    for i in x:
        if i['department'] == 'Sound':
            if(i['id'] not in list1):
                list1.append(i['id'])
    return list1
mov['sound']=mov['crew'].apply(sound)

In [21]:
def art(x):
    list1 = []
    for i in x:
        if i['department'] == 'Art':
            if(i['id'] not in list1):
                list1.append(i['id'])
    return list1

def production(x):
    list1 = []
    for i in x:
        if i['department'] == 'Production':
            if(i['id'] not in list1):
                list1.append(i['id'])
    return list1

def visualeffects(x):
    list1 = []
    for i in x:
        if i['department'] == 'Visual Effects':
            if(i['id'] not in list1):
                list1.append(i['id'])
    return list1

def costume(x):
    list1 = []
    for i in x:
        if i['department'] == 'Costume & Make-Up':
            if(i['id'] not in list1):
                list1.append(i['id'])
    return list1

def camera(x):
    list1 = []
    for i in x:
        if i['department'] == 'Camera':
            if(i['id'] not in list1):
                list1.append(i['id'])
    return list1
def crew(x):
    list1 = []
    for i in x:
        if i['department'] == 'Crew':
            if(i['id'] not in list1):
                list1.append(i['id'])
    return list1

def lighting(x):
    list1 = []
    for i in x:
        if i['department'] == 'Lighting':
            if(i['id'] not in list1):
                list1.append(i['id'])
    return list1

def writing(x):
    list1 = []
    for i in x:
        if i['department'] == 'Writing':
            if(i['id'] not in list1):
                list1.append(i['id'])
    return list1

def directing(x):
    list1 = []
    for i in x:
        if i['department'] == 'Directing':
            if(i['id'] not in list1):
                list1.append(i['id'])
    return list1

In [22]:
mov['art']=mov['crew'].apply(art) 
mov['production']=mov['crew'].apply(production) 
mov['visual_effects']=mov['crew'].apply(visualeffects) 
mov['costume']=mov['crew'].apply(costume) 
mov['camera']=mov['crew'].apply(camera)  
mov['lighting']=mov['crew'].apply(lighting) 
mov['writing']=mov['crew'].apply(writing) 
mov['crew_member']=mov['crew'].apply(crew)
mov['directing']=mov['crew'].apply(directing)

In [307]:
mov.head(1)

,movie_id,title,cast,crew,main_cast,director,editing,sound,art,production,visual_effects,costume,camera,lighting,writing,crew_member,directing
0,19995,Avatar,"[{'cast_id': 242, 'character': 'Jake Sully', '...","[{'credit_id': '52fe48009251416c750aca23', 'de...","[65731, 8691, 10205, 32747, 17647, 1771, 59231...",[2710],"[1721, 2710, 58871, 1352422, 1376899, 1376901,...","[900, 1729, 6883, 8159, 8160, 8163, 1360103, 1...","[496, 7236, 6878, 9618, 12653, 14350, 42281, 3...","[1262, 2710, 6347, 8529, 20294, 1016177, 14017...","[6690, 113145, 93214, 957874, 1204668, 1206410...","[8527, 17675, 29067, 1071680, 1202850, 1310064...","[18265, 33302, 72201, 1177364, 1398970, 1401806]","[1401805, 1401807, 1453938]",[2710],"[42288, 58188, 89714, 122607, 236696, 956198, ...",[2710]

In [309]:
mov.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 17 columns):
movie_id          4803 non-null int64
title             4803 non-null object
cast              4803 non-null object
crew              4803 non-null object
main_cast         4803 non-null object
director          4803 non-null object
editing           4803 non-null object
sound             4803 non-null object
art               4803 non-null object
production        4803 non-null object
visual_effects    4803 non-null object
costume           4803 non-null object
camera            4803 non-null object
lighting          4803 non-null object
writing           4803 non-null object
crew_member       4803 non-null object
directing         4803 non-null object
dtypes: int64(1), object(16)
memory usage: 638.0+ KB

In [25]:
movies.to_csv('movies_1206id.csv', sep=',', header=True, index=False)
mov.to_csv('mov_1206id.csv', sep = ',', header=True, index=False)
# dataset=movies.merge(mov,left_on='id',right_on='movie_id',how='left')
for col in ['main_cast','director', 'editing', 'sound', 'art', 'production', 
            'visual_effects', 'costume', 'camera', 'lighting', 'writing', 'crew_member']:
    movies[col] = mov[col]
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,editing,sound,art,production,visual_effects,costume,camera,lighting,writing,crew_member
0,237000000,"[Action, Adventure, Fantasy, Science Fiction]",http://www.avatarmovie.com/,19995,"[culture clash, future, space war, space colon...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[289, 306, 444, 574]",...,"[1721, 2710, 58871, 1352422, 1376899, 1376901,...","[900, 1729, 6883, 8159, 8160, 8163, 1360103, 1...","[496, 7236, 6878, 9618, 12653, 14350, 42281, 3...","[1262, 2710, 6347, 8529, 20294, 1016177, 14017...","[6690, 113145, 93214, 957874, 1204668, 1206410...","[8527, 17675, 29067, 1071680, 1202850, 1310064...","[18265, 33302, 72201, 1177364, 1398970, 1401806]","[1401805, 1401807, 1453938]",[2710],"[42288, 58188, 89714, 122607, 236696, 956198, ..."
1,300000000,"[Adventure, Fantasy, Action]",http://disney.go.com/disneypictures/pirates/,285,"[ocean, drug abuse, exotic island, east india ...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[2, 130, 19936]",...,"[1721, 1722]","[947, 5132, 1368884, 1399327, 1534197]","[1226, 553, 4032, 146439]","[770, 2444, 2445, 2446, 2447, 2448, 2215, 3311]",[],"[4033, 4034, 406204]",[120],[],"[1705, 1706]","[1259516, 1336716, 1368867]"
2,245000000,"[Action, Adventure, Crime]",http://www.sonypictures.com/movies/spectre/,206647,"[spy, based on novel, secret agent, sequel, mi...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[5, 10761, 69434]",...,"[3904, 1399862, 1408363, 1548406]","[153, 7538, 40827, 14764, 14765, 66941, 133837...","[8384, 4248, 23425, 23491, 979698, 986687, 129...","[8784, 10496, 10666, 11268, 36108, 10876, 1090...","[1029804, 1338241, 1341741, 1391691, 1398100, ...","[11227, 1087452, 1099281, 1315700, 1319160, 14...","[61851, 74401, 937946, 1118711, 1377503, 13888...","[1414096, 1553236, 1582109]","[932, 9856, 10783, 10782, 21339]","[23774, 239885, 1024842, 1401147, 1411323, 141..."
3,250000000,"[Action, Crime, Drama, Thriller]",http://www.thedarkknightrises.com/,49026,"[dc comics, crime fighter, terrorist, secret i...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[923, 6194, 9993, 9996]",...,"[3904, 1050930, 1417840, 1440853, 1525908, 155...","[947, 52193, 68016, 138618, 230436, 932186, 11...","[12039, 14762, 15327, 15328, 17677, 62560, 311...","[282, 525, 556, 561, 10949, 10951, 54211, 7580...","[92231, 1155668, 1408347, 1417821, 1417826, 14...","[9991, 10714, 1046614, 1319744, 1322015, 13361...","[559, 1357064, 1357066, 1399071, 1399876, 1404...","[35630, 40120, 1417832, 1417833, 1417835, 1532...","[525, 527, 3893, 3794]","[9568, 57569, 61329, 81687, 122549, 142157, 20..."
4,260000000,"[Action, Adventure, Science Fiction]",http://movies.disney.com/john-carter,49529,"[based on novel, mars, medallion, space travel...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,[2],...,"[6958, 8158, 1376901, 1710258]","[3996, 8166, 15347, 15354, 28241, 105780, 1386...","[12039, 14762, 15327, 34513, 17677, 18925, 234...","[490, 2073, 51557, 64449, 72752, 72753, 91055,...","[122274, 1081073, 1367497, 1408379, 1428901]","[8412, 15017, 17675, 29233, 61996, 406204, 967...","[15348, 91912, 1399467, 1400535, 1412205, 1430...","[1390367, 1399475]","[7, 15776, 67758, 126638]","[7879, 12895, 12897, 39624, 1034755, 1339450, ..."

In [23]:
# 加入category

In [26]:
col_name = movies.columns.tolist()
col_name.insert(0,'category')
print(col_name)

['category', 'budget', 'genres', 'homepage', 'id', 'keywords', 'original_language', 'original_title', 'overview', 'popularity', 'production_companies', 'production_countries', 'release_date', 'revenue', 'runtime', 'spoken_languages', 'status', 'tagline', 'title', 'vote_average', 'vote_count', 'main_cast', 'director', 'editing', 'sound', 'art', 'production', 'visual_effects', 'costume', 'camera', 'lighting', 'writing', 'crew_member']

In [27]:
movies = movies.reindex(columns=col_name)

In [336]:
movies['category'] = 'Movie'

In [38]:
# 这个算法太慢&维度太高
def uniqueList(col):
    List = []
    for index, row in movies.iterrows():
        col_all = row[col]
        for cell in col_all:
            if cell not in List:
                List.append(cell)
    if List[-1] == '':
        return List[0:-1]
    else:
        return List

def binary(unique_list, cell_list):
    binaryList=[]
    for one in unique_list:
        if one in cell_list:
            binaryList.append(1)
        else:
            binaryList.append(0)
    return binaryList

In [36]:
genresList = uniqueList('genres')

In [32]:
castList = uniqueList('main_cast')

In [42]:
movies['genres_bin'] = movies['genres'].apply(lambda x: binary(genresList,x))

In [52]:
movies['genres_bin'][0]

[1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [43]:
movies['cast_bin'] = movies['main_cast'].apply(lambda x: binary(castList,x))

In [308]:
movies['cast_bin'].head(3)

0    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, ...
1    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, ...
2    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
Name: cast_bin, dtype: object

In [152]:
directorList = uniqueList('director')

In [154]:
movies['director_bin'] = movies['director'].apply(lambda x: binary(directorList,x))

In [155]:
movies['director_bin'].head()

0    [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
1    [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
2    [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
3    [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
4    [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
Name: director_bin, dtype: object

In [156]:
movies.to_csv('movieNode_1206.csv', sep=',', header=True, index=False)

In [53]:
# dst = pd.read_csv('movieNode_1206.csv')
#存入csv后都会变成字符串，再取出需要重新处理为list
# dst['production_companies'].str.replace('[','').str.replace(']','').str.split(', ')

In [116]:
# 电影-主题表

In [136]:
mov2 = movies['genres_bin']

In [137]:
tmp = [line for line in mov2]
tmp_arr = np.array(tmp)
movie_genres = pd.DataFrame(data = tmp_arr, columns = genresList)

In [138]:
movie_genres.head()

,Action,Adventure,Fantasy,Science Fiction,Crime,Drama,Thriller,Animation,Family,Western,Comedy,Romance,Horror,Mystery,History,War,Music,Documentary,Foreign,TV Movie
0,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,1,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,1,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0
4,1,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [132]:
colname = movie_genres.columns.tolist()
colname.insert(0,'movie_id')

In [133]:
movie_genres = movie_genres.reindex(columns=colname)
movie_genres['movie_id'] = movies['id']

In [134]:
movie_genres.head()

,movie_id,Action,Adventure,Fantasy,Science Fiction,Crime,Drama,Thriller,Animation,Family,...,Comedy,Romance,Horror,Mystery,History,War,Music,Documentary,Foreign,TV Movie
0,19995,1,1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,285,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,206647,1,1,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,49026,1,0,0,0,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,49529,1,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [135]:
movie_genres.to_csv('movie_genres.csv',sep=',', header=True, index=False)

In [300]:
movie_genres.T.head(3)

,0,1,2,3,4,5,6,7,8,9,...,4793,4794,4795,4796,4797,4798,4799,4800,4801,4802
Action,1,1,1,1,1,1,0,1,0,1,...,0,0,0,0,0,1,0,0,0,0
Adventure,1,1,1,0,1,1,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0
Fantasy,1,1,0,0,0,1,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
#电影-主要演员

In [140]:
mov3 = movies['cast_bin']
tmp1 = [line for line in mov3]
tmp_arr1 = np.array(tmp1)
movie_cast = pd.DataFrame(data = tmp_arr1, columns = castList)

In [142]:
colname1 = movie_cast.columns.tolist()
colname1.insert(0,'movie_id')
movie_cast = movie_cast.reindex(columns=colname1)
movie_cast['movie_id'] = movies['id']

In [151]:
movie_cast.to_csv('movie_cast.csv',sep=',', header=True, index=False)

In [298]:
movie_cast.head()

,movie_id,65731,8691,10205,32747,17647,1771,59231,30485,15853,...,1192733,1192734,1293343,1066358,17188,1257819,1037844,1395490,85563,155007
0,19995,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
1,285,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,206647,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,49026,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,49529,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
#电影-导演

In [157]:
mov4 = movies['director_bin']
tmp2 = [line for line in mov4]
tmp_arr2 = np.array(tmp2)
movie_director = pd.DataFrame(data = tmp_arr2, columns = directorList)

In [158]:
colname2 = movie_director.columns.tolist()
colname2.insert(0,'movie_id')
movie_director = movie_director.reindex(columns=colname2)
movie_director['movie_id'] = movies['id']

In [159]:
movie_director.head()

,movie_id,2710,1704,39,525,7,7623,76595,121830,12891,...,1398500,1171387,77465,76624,1174437,1174438,1219158,208138,85563,997560
0,19995,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,285,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,206647,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,49026,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,49529,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [160]:
movie_director.to_csv('movie_director.csv',sep=',', header=True, index=False)

In [ ]:
# Cast_node

In [163]:
mov['cast'][0][0]

{'cast_id': 242,
 'character': 'Jake Sully',
 'credit_id': '5602a8a7c3a3685532001c9a',
 'gender': 2,
 'id': 65731,
 'name': 'Sam Worthington',
 'order': 0}

In [179]:
castNode = pd.DataFrame(data = mov['cast'][0])
colname3 = castNode.columns.tolist()
colname3.insert(7,'movie_id')
castNode = castNode.reindex(columns=colname3)
castNode['movie_id'] = movies['id'][0]

In [182]:
for i in range(1,4803):
    tempNode = pd.DataFrame(data = mov['cast'][i])
    tempNode = tempNode.reindex(columns=colname3)
    tempNode['movie_id'] = movies['id'][i]
    castNode = castNode.append(tempNode)
    print("i=",i)

i= 1
i= 2
i= 3
i= 4
i= 5
i= 6
i= 7
i= 8
i= 9
i= 10
i= 11
i= 12
i= 13
i= 14
i= 15
i= 16
i= 17
i= 18
i= 19
i= 20
i= 21
i= 22
i= 23
i= 24
i= 25
i= 26
i= 27
i= 28
i= 29
i= 30
i= 31
i= 32
i= 33
i= 34
i= 35
i= 36
i= 37
i= 38
i= 39
i= 40
i= 41
i= 42
i= 43
i= 44
i= 45
i= 46
i= 47
i= 48
i= 49
i= 50
i= 51
i= 52
i= 53
i= 54
i= 55
i= 56
i= 57
i= 58
i= 59
i= 60
i= 61
i= 62
i= 63
i= 64
i= 65
i= 66
i= 67
i= 68
i= 69
i= 70
i= 71
i= 72
i= 73
i= 74
i= 75
i= 76
i= 77
i= 78
i= 79
i= 80
i= 81
i= 82
i= 83
i= 84
i= 85
i= 86
i= 87
i= 88
i= 89
i= 90
i= 91
i= 92
i= 93
i= 94
i= 95
i= 96
i= 97
i= 98
i= 99
i= 100
i= 101
i= 102
i= 103
i= 104
i= 105
i= 106
i= 107
i= 108
i= 109
i= 110
i= 111
i= 112
i= 113
i= 114
i= 115
i= 116
i= 117
i= 118
i= 119
i= 120
i= 121
i= 122
i= 123
i= 124
i= 125
i= 126
i= 127
i= 128
i= 129
i= 130
i= 131
i= 132
i= 133
i= 134
i= 135
i= 136
i= 137
i= 138
i= 139
i= 140
i= 141
i= 142
i= 143
i= 144
i= 145
i= 146
i= 147
i= 148
i= 149
i= 150
i= 151
i= 152
i= 153
i= 154
i= 155
i= 156
i= 157
i= 158
i= 159
i= 160
i= 161
i= 162
i= 163
i= 164
i= 165
i= 166
i= 167
i= 168
i= 169
i= 170
i= 171
i= 172
i= 173
i= 174
i= 175
i= 176
i= 177
i= 178
i= 179
i= 180
i= 181
i= 182
i= 183
i= 184
i= 185
i= 186
i= 187
i= 188
i= 189
i= 190
i= 191
i= 192
i= 193
i= 194
i= 195
i= 196
i= 197
i= 198
i= 199
i= 200
i= 201
i= 202
i= 203
i= 204
i= 205
i= 206
i= 207
i= 208
i= 209
i= 210
i= 211
i= 212
i= 213
i= 214
i= 215
i= 216
i= 217
i= 218
i= 219
i= 220
i= 221
i= 222
i= 223
i= 224
i= 225
i= 226
i= 227
i= 228
i= 229
i= 230
i= 231
i= 232
i= 233
i= 234
i= 235
i= 236
i= 237
i= 238
i= 239
i= 240
i= 241
i= 242
i= 243
i= 244
i= 245
i= 246
i= 247
i= 248
i= 249
i= 250
i= 251
i= 252
i= 253
i= 254
i= 255
i= 256
i= 257
i= 258
i= 259
i= 260
i= 261
i= 262
i= 263
i= 264
i= 265
i= 266
i= 267
i= 268
i= 269
i= 270
i= 271
i= 272
i= 273
i= 274
i= 275
i= 276
i= 277
i= 278
i= 279
i= 280
i= 281
i= 282
i= 283
i= 284
i= 285
i= 286
i= 287
i= 288
i= 289
i= 290
i= 291
i= 292
i= 293
i= 294
i= 295
i= 296
i= 297
i= 298
i= 299
i= 300
i= 301
i= 302
i= 303
i= 304
i= 305
i= 306
i= 307
i= 308
i= 309
i= 310
i= 311
i= 312
i= 313
i= 314
i= 315
i= 316
i= 317
i= 318
i= 319
i= 320
i= 321
i= 322
i= 323
i= 324
i= 325
i= 326
i= 327
i= 328
i= 329
i= 330
i= 331
i= 332
i= 333
i= 334
i= 335
i= 336
i= 337
i= 338
i= 339
i= 340
i= 341
i= 342
i= 343
i= 344
i= 345
i= 346
i= 347
i= 348
i= 349
i= 350
i= 351
i= 352
i= 353
i= 354
i= 355
i= 356
i= 357
i= 358
i= 359
i= 360
i= 361
i= 362
i= 363
i= 364
i= 365
i= 366
i= 367
i= 368
i= 369
i= 370
i= 371
i= 372
i= 373
i= 374
i= 375
i= 376
i= 377
i= 378
i= 379
i= 380
i= 381
i= 382
i= 383
i= 384
i= 385
i= 386
i= 387
i= 388
i= 389
i= 390
i= 391
i= 392
i= 393
i= 394
i= 395
i= 396
i= 397
i= 398
i= 399
i= 400
i= 401
i= 402
i= 403
i= 404
i= 405
i= 406
i= 407
i= 408
i= 409
i= 410
i= 411
i= 412
i= 413
i= 414
i= 415
i= 416
i= 417
i= 418
i= 419
i= 420
i= 421
i= 422
i= 423
i= 424
i= 425
i= 426
i= 427
i= 428
i= 429
i= 430
i= 431
i= 432
i= 433
i= 434
i= 435
i= 436
i= 437
i= 438
i= 439
i= 440
i= 441
i= 442
i= 443
i= 444
i= 445
i= 446
i= 447
i= 448
i= 449
i= 450
i= 451
i= 452
i= 453
i= 454
i= 455
i= 456
i= 457
i= 458
i= 459
i= 460
i= 461
i= 462
i= 463
i= 464
i= 465
i= 466
i= 467
i= 468
i= 469
i= 470
i= 471
i= 472
i= 473
i= 474
i= 475
i= 476
i= 477
i= 478
i= 479
i= 480
i= 481
i= 482
i= 483
i= 484
i= 485
i= 486
i= 487
i= 488
i= 489
i= 490
i= 491
i= 492
i= 493
i= 494
i= 495
i= 496
i= 497
i= 498
i= 499
i= 500
i= 501
i= 502
i= 503
i= 504
i= 505
i= 506
i= 507
i= 508
i= 509
i= 510
i= 511
i= 512
i= 513
i= 514
i= 515
i= 516
i= 517
i= 518
i= 519
i= 520
i= 521
i= 522
i= 523
i= 524
i= 525
i= 526
i= 527
i= 528
i= 529
i= 530
i= 531
i= 532
i= 533
i= 534
i= 535
i= 536
i= 537
i= 538
i= 539
i= 540
i= 541
i= 542
i= 543
i= 544
i= 545
i= 546
i= 547
i= 548
i= 549
i= 550
i= 551
i= 552
i= 553
i= 554
i= 555
i= 556
i= 557
i= 558
i= 559
i= 560
i= 561
i= 562
i= 563
i= 564
i= 565
i= 566
i= 567
i= 568
i= 569
i= 570
i= 571
i= 572
i= 573
i= 574
i= 575
i= 576
i= 577
i= 578
i= 579
i= 580
i= 581
i= 582
i= 583
i= 584
i= 585
i= 586
i= 587
i= 588
i= 589
i= 590
i= 591
i= 592
i= 593
i= 594
i= 595
i= 596
i= 597
i= 598
i= 599
i= 600
i= 601
i= 602
i= 603
i= 604
i= 605
i= 606
i= 607
i= 608
i= 609
i= 610
i= 611
i= 612
i= 613
i= 614
i= 615
i= 616
i= 617
i= 618
i= 619
i= 620
i= 621
i= 622
i= 623
i= 624
i= 625
i= 626
i= 627
i= 628
i= 629
i= 630
i= 631
i= 632
i= 633
i= 634
i= 635
i= 636
i= 637
i= 638
i= 639
i= 640
i= 641
i= 642
i= 643
i= 644
i= 645
i= 646
i= 647
i= 648
i= 649
i= 650
i= 651
i= 652
i= 653
i= 654
i= 655
i= 656
i= 657
i= 658
i= 659
i= 660
i= 661
i= 662
i= 663
i= 664
i= 665
i= 666
i= 667
i= 668
i= 669
i= 670
i= 671
i= 672
i= 673
i= 674
i= 675
i= 676
i= 677
i= 678
i= 679
i= 680
i= 681
i= 682
i= 683
i= 684
i= 685
i= 686
i= 687
i= 688
i= 689
i= 690
i= 691
i= 692
i= 693
i= 694
i= 695
i= 696
i= 697
i= 698
i= 699
i= 700
i= 701
i= 702
i= 703
i= 704
i= 705
i= 706
i= 707
i= 708
i= 709
i= 710
i= 711
i= 712
i= 713
i= 714
i= 715
i= 716
i= 717
i= 718
i= 719
i= 720
i= 721
i= 722
i= 723
i= 724
i= 725
i= 726
i= 727
i= 728
i= 729
i= 730
i= 731
i= 732
i= 733
i= 734
i= 735
i= 736
i= 737
i= 738
i= 739
i= 740
i= 741
i= 742
i= 743
i= 744
i= 745
i= 746
i= 747
i= 748
i= 749
i= 750
i= 751
i= 752
i= 753
i= 754
i= 755
i= 756
i= 757
i= 758
i= 759
i= 760
i= 761
i= 762
i= 763
i= 764
i= 765
i= 766
i= 767
i= 768
i= 769
i= 770
i= 771
i= 772
i= 773
i= 774
i= 775
i= 776
i= 777
i= 778
i= 779
i= 780
i= 781
i= 782
i= 783
i= 784
i= 785
i= 786
i= 787
i= 788
i= 789
i= 790
i= 791
i= 792
i= 793
i= 794
i= 795
i= 796
i= 797
i= 798
i= 799
i= 800
i= 801
i= 802
i= 803
i= 804
i= 805
i= 806
i= 807
i= 808
i= 809
i= 810
i= 811
i= 812
i= 813
i= 814
i= 815
i= 816
i= 817
i= 818
i= 819
i= 820
i= 821
i= 822
i= 823
i= 824
i= 825
i= 826
i= 827
i= 828
i= 829
i= 830
i= 831
i= 832
i= 833
i= 834
i= 835
i= 836
i= 837
i= 838
i= 839
i= 840
i= 841
i= 842
i= 843
i= 844
i= 845
i= 846
i= 847
i= 848
i= 849
i= 850
i= 851
i= 852
i= 853
i= 854
i= 855
i= 856
i= 857
i= 858
i= 859
i= 860
i= 861
i= 862
i= 863
i= 864
i= 865
i= 866
i= 867
i= 868
i= 869
i= 870
i= 871
i= 872
i= 873
i= 874
i= 875
i= 876
i= 877
i= 878
i= 879
i= 880
i= 881
i= 882
i= 883
i= 884
i= 885
i= 886
i= 887
i= 888
i= 889
i= 890
i= 891
i= 892
i= 893
i= 894
i= 895
i= 896
i= 897
i= 898
i= 899
i= 900
i= 901
i= 902
i= 903
i= 904
i= 905
i= 906
i= 907
i= 908
i= 909
i= 910
i= 911
i= 912
i= 913
i= 914
i= 915
i= 916
i= 917
i= 918
i= 919
i= 920
i= 921
i= 922
i= 923
i= 924
i= 925
i= 926
i= 927
i= 928
i= 929
i= 930
i= 931
i= 932
i= 933
i= 934
i= 935
i= 936
i= 937
i= 938
i= 939
i= 940
i= 941
i= 942
i= 943
i= 944
i= 945
i= 946
i= 947
i= 948
i= 949
i= 950
i= 951
i= 952
i= 953
i= 954
i= 955
i= 956
i= 957
i= 958
i= 959
i= 960
i= 961
i= 962
i= 963
i= 964
i= 965
i= 966
i= 967
i= 968
i= 969
i= 970
i= 971
i= 972
i= 973
i= 974
i= 975
i= 976
i= 977
i= 978
i= 979
i= 980
i= 981
i= 982
i= 983
i= 984
i= 985
i= 986
i= 987
i= 988
i= 989
i= 990
i= 991
i= 992
i= 993
i= 994
i= 995
i= 996
i= 997
i= 998
i= 999
i= 1000
i= 1001
i= 1002
i= 1003
i= 1004
i= 1005
i= 1006
i= 1007
i= 1008
i= 1009
i= 1010
i= 1011
i= 1012
i= 1013
i= 1014
i= 1015
i= 1016
i= 1017
i= 1018
i= 1019
i= 1020
i= 1021
i= 1022
i= 1023
i= 1024
i= 1025
i= 1026
i= 1027
i= 1028
i= 1029
i= 1030
i= 1031
i= 1032
i= 1033
i= 1034
i= 1035
i= 1036
i= 1037
i= 1038
i= 1039
i= 1040
i= 1041
i= 1042
i= 1043
i= 1044
i= 1045
i= 1046
i= 1047
i= 1048
i= 1049
i= 1050
i= 1051
i= 1052
i= 1053
i= 1054
i= 1055
i= 1056
i= 1057
i= 1058
i= 1059
i= 1060
i= 1061
i= 1062
i= 1063
i= 1064
i= 1065
i= 1066
i= 1067
i= 1068
i= 1069
i= 1070
i= 1071
i= 1072
i= 1073
i= 1074
i= 1075
i= 1076
i= 1077
i= 1078
i= 1079
i= 1080
i= 1081
i= 1082
i= 1083
i= 1084
i= 1085
i= 1086
i= 1087
i= 1088
i= 1089
i= 1090
i= 1091
i= 1092
i= 1093
i= 1094
i= 1095
i= 1096
i= 1097
i= 1098
i= 1099
i= 1100
i= 1101
i= 1102
i= 1103
i= 1104
i= 1105
i= 1106
i= 1107
i= 1108
i= 1109
i= 1110
i= 1111
i= 1112
i= 1113
i= 1114
i= 1115
i= 1116
i= 1117
i= 1118
i= 1119
i= 1120
i= 1121
i= 1122
i= 1123
i= 1124
i= 1125
i= 1126
i= 1127
i= 1128
i= 1129
i= 1130
i= 1131
i= 1132
i= 1133
i= 1134
i= 1135
i= 1136
i= 1137
i= 1138
i= 1139
i= 1140
i= 1141
i= 1142
i= 1143
i= 1144
i= 1145
i= 1146
i= 1147
i= 1148
i= 1149
i= 1150
i= 1151
i= 1152
i= 1153
i= 1154
i= 1155
i= 1156
i= 1157
i= 1158
i= 1159
i= 1160
i= 1161
i= 1162
i= 1163

i= 1164
i= 1165
i= 1166
i= 1167
i= 1168
i= 1169
i= 1170
i= 1171
i= 1172
i= 1173
i= 1174
i= 1175
i= 1176
i= 1177
i= 1178
i= 1179
i= 1180
i= 1181
i= 1182
i= 1183
i= 1184
i= 1185
i= 1186
i= 1187
i= 1188
i= 1189
i= 1190
i= 1191
i= 1192
i= 1193
i= 1194
i= 1195
i= 1196
i= 1197
i= 1198
i= 1199
i= 1200
i= 1201
i= 1202
i= 1203
i= 1204
i= 1205
i= 1206
i= 1207
i= 1208
i= 1209
i= 1210
i= 1211
i= 1212
i= 1213
i= 1214
i= 1215
i= 1216
i= 1217
i= 1218
i= 1219
i= 1220
i= 1221
i= 1222
i= 1223
i= 1224
i= 1225
i= 1226
i= 1227
i= 1228
i= 1229
i= 1230
i= 1231
i= 1232
i= 1233
i= 1234
i= 1235
i= 1236
i= 1237
i= 1238
i= 1239
i= 1240
i= 1241
i= 1242
i= 1243
i= 1244
i= 1245
i= 1246
i= 1247
i= 1248
i= 1249
i= 1250
i= 1251
i= 1252
i= 1253
i= 1254
i= 1255
i= 1256
i= 1257
i= 1258
i= 1259
i= 1260
i= 1261
i= 1262
i= 1263
i= 1264
i= 1265
i= 1266
i= 1267
i= 1268
i= 1269
i= 1270
i= 1271
i= 1272
i= 1273
i= 1274
i= 1275
i= 1276
i= 1277
i= 1278
i= 1279
i= 1280
i= 1281
i= 1282
i= 1283
i= 1284
i= 1285
i= 1286
i= 1287
i= 1288
i= 1289
i= 1290
i= 1291
i= 1292
i= 1293
i= 1294
i= 1295
i= 1296
i= 1297
i= 1298
i= 1299
i= 1300
i= 1301
i= 1302
i= 1303
i= 1304
i= 1305
i= 1306
i= 1307
i= 1308
i= 1309
i= 1310
i= 1311
i= 1312
i= 1313
i= 1314
i= 1315
i= 1316
i= 1317
i= 1318
i= 1319
i= 1320
i= 1321
i= 1322
i= 1323
i= 1324
i= 1325
i= 1326
i= 1327
i= 1328
i= 1329
i= 1330
i= 1331
i= 1332
i= 1333
i= 1334
i= 1335
i= 1336
i= 1337
i= 1338
i= 1339
i= 1340
i= 1341
i= 1342
i= 1343
i= 1344
i= 1345
i= 1346
i= 1347
i= 1348
i= 1349
i= 1350
i= 1351
i= 1352
i= 1353
i= 1354
i= 1355
i= 1356
i= 1357
i= 1358
i= 1359
i= 1360
i= 1361
i= 1362
i= 1363
i= 1364
i= 1365
i= 1366
i= 1367
i= 1368
i= 1369
i= 1370
i= 1371
i= 1372
i= 1373
i= 1374
i= 1375
i= 1376
i= 1377
i= 1378
i= 1379
i= 1380
i= 1381
i= 1382
i= 1383
i= 1384
i= 1385
i= 1386
i= 1387
i= 1388
i= 1389
i= 1390
i= 1391
i= 1392
i= 1393
i= 1394
i= 1395
i= 1396
i= 1397
i= 1398
i= 1399
i= 1400
i= 1401
i= 1402
i= 1403
i= 1404
i= 1405
i= 1406
i= 1407
i= 1408
i= 1409
i= 1410
i= 1411
i= 1412
i= 1413
i= 1414
i= 1415
i= 1416
i= 1417
i= 1418
i= 1419
i= 1420
i= 1421
i= 1422
i= 1423
i= 1424
i= 1425
i= 1426
i= 1427
i= 1428
i= 1429
i= 1430
i= 1431
i= 1432
i= 1433
i= 1434
i= 1435
i= 1436
i= 1437
i= 1438
i= 1439
i= 1440
i= 1441
i= 1442
i= 1443
i= 1444
i= 1445
i= 1446
i= 1447
i= 1448
i= 1449
i= 1450
i= 1451
i= 1452
i= 1453
i= 1454
i= 1455
i= 1456
i= 1457
i= 1458
i= 1459
i= 1460
i= 1461
i= 1462
i= 1463
i= 1464
i= 1465
i= 1466
i= 1467
i= 1468
i= 1469
i= 1470
i= 1471
i= 1472
i= 1473
i= 1474
i= 1475
i= 1476
i= 1477
i= 1478
i= 1479
i= 1480
i= 1481
i= 1482
i= 1483
i= 1484
i= 1485
i= 1486
i= 1487
i= 1488
i= 1489
i= 1490
i= 1491
i= 1492
i= 1493
i= 1494
i= 1495
i= 1496
i= 1497
i= 1498
i= 1499
i= 1500
i= 1501
i= 1502
i= 1503
i= 1504
i= 1505
i= 1506
i= 1507
i= 1508
i= 1509
i= 1510
i= 1511
i= 1512
i= 1513
i= 1514
i= 1515
i= 1516
i= 1517
i= 1518
i= 1519
i= 1520
i= 1521
i= 1522
i= 1523
i= 1524
i= 1525
i= 1526
i= 1527
i= 1528
i= 1529
i= 1530
i= 1531
i= 1532
i= 1533
i= 1534
i= 1535
i= 1536
i= 1537
i= 1538
i= 1539
i= 1540
i= 1541
i= 1542
i= 1543
i= 1544
i= 1545
i= 1546
i= 1547
i= 1548
i= 1549
i= 1550
i= 1551
i= 1552
i= 1553
i= 1554
i= 1555
i= 1556
i= 1557
i= 1558
i= 1559
i= 1560
i= 1561
i= 1562
i= 1563
i= 1564
i= 1565
i= 1566
i= 1567
i= 1568
i= 1569
i= 1570
i= 1571
i= 1572
i= 1573
i= 1574
i= 1575
i= 1576
i= 1577
i= 1578
i= 1579
i= 1580
i= 1581
i= 1582
i= 1583
i= 1584
i= 1585
i= 1586
i= 1587
i= 1588
i= 1589
i= 1590
i= 1591
i= 1592
i= 1593
i= 1594
i= 1595
i= 1596
i= 1597
i= 1598
i= 1599
i= 1600
i= 1601
i= 1602
i= 1603
i= 1604
i= 1605
i= 1606
i= 1607
i= 1608
i= 1609
i= 1610
i= 1611
i= 1612
i= 1613
i= 1614
i= 1615
i= 1616
i= 1617
i= 1618
i= 1619
i= 1620
i= 1621
i= 1622
i= 1623
i= 1624
i= 1625
i= 1626
i= 1627
i= 1628
i= 1629
i= 1630
i= 1631
i= 1632
i= 1633
i= 1634
i= 1635
i= 1636
i= 1637
i= 1638
i= 1639
i= 1640
i= 1641
i= 1642
i= 1643
i= 1644
i= 1645
i= 1646
i= 1647
i= 1648
i= 1649
i= 1650
i= 1651
i= 1652
i= 1653
i= 1654
i= 1655
i= 1656
i= 1657
i= 1658
i= 1659
i= 1660
i= 1661
i= 1662
i= 1663
i= 1664
i= 1665
i= 1666
i= 1667
i= 1668
i= 1669
i= 1670
i= 1671
i= 1672
i= 1673
i= 1674
i= 1675
i= 1676
i= 1677
i= 1678
i= 1679
i= 1680
i= 1681
i= 1682
i= 1683
i= 1684
i= 1685
i= 1686
i= 1687
i= 1688
i= 1689
i= 1690
i= 1691
i= 1692
i= 1693
i= 1694
i= 1695
i= 1696
i= 1697
i= 1698
i= 1699
i= 1700
i= 1701
i= 1702
i= 1703
i= 1704
i= 1705
i= 1706
i= 1707
i= 1708
i= 1709
i= 1710
i= 1711
i= 1712
i= 1713
i= 1714
i= 1715
i= 1716
i= 1717
i= 1718
i= 1719
i= 1720
i= 1721
i= 1722
i= 1723
i= 1724
i= 1725
i= 1726
i= 1727
i= 1728
i= 1729
i= 1730
i= 1731
i= 1732
i= 1733
i= 1734
i= 1735
i= 1736
i= 1737
i= 1738
i= 1739
i= 1740
i= 1741
i= 1742
i= 1743
i= 1744
i= 1745
i= 1746
i= 1747
i= 1748
i= 1749
i= 1750
i= 1751
i= 1752
i= 1753
i= 1754
i= 1755
i= 1756
i= 1757
i= 1758
i= 1759
i= 1760
i= 1761
i= 1762
i= 1763
i= 1764
i= 1765
i= 1766
i= 1767
i= 1768
i= 1769
i= 1770
i= 1771
i= 1772
i= 1773
i= 1774
i= 1775
i= 1776
i= 1777
i= 1778
i= 1779
i= 1780
i= 1781
i= 1782
i= 1783
i= 1784
i= 1785
i= 1786
i= 1787
i= 1788
i= 1789
i= 1790
i= 1791
i= 1792
i= 1793
i= 1794
i= 1795
i= 1796
i= 1797
i= 1798
i= 1799
i= 1800
i= 1801
i= 1802
i= 1803
i= 1804
i= 1805
i= 1806
i= 1807
i= 1808
i= 1809
i= 1810
i= 1811
i= 1812
i= 1813
i= 1814
i= 1815
i= 1816
i= 1817
i= 1818
i= 1819
i= 1820
i= 1821
i= 1822
i= 1823
i= 1824
i= 1825
i= 1826
i= 1827
i= 1828
i= 1829
i= 1830
i= 1831
i= 1832
i= 1833
i= 1834
i= 1835
i= 1836
i= 1837
i= 1838
i= 1839
i= 1840
i= 1841
i= 1842
i= 1843
i= 1844
i= 1845
i= 1846
i= 1847
i= 1848
i= 1849
i= 1850
i= 1851
i= 1852
i= 1853
i= 1854
i= 1855
i= 1856
i= 1857
i= 1858
i= 1859
i= 1860
i= 1861
i= 1862
i= 1863
i= 1864
i= 1865
i= 1866
i= 1867
i= 1868
i= 1869
i= 1870
i= 1871
i= 1872
i= 1873
i= 1874
i= 1875
i= 1876
i= 1877
i= 1878
i= 1879
i= 1880
i= 1881
i= 1882
i= 1883
i= 1884
i= 1885
i= 1886
i= 1887
i= 1888
i= 1889
i= 1890
i= 1891
i= 1892
i= 1893
i= 1894
i= 1895
i= 1896
i= 1897
i= 1898
i= 1899
i= 1900
i= 1901
i= 1902
i= 1903
i= 1904
i= 1905
i= 1906
i= 1907
i= 1908
i= 1909
i= 1910
i= 1911
i= 1912
i= 1913
i= 1914
i= 1915
i= 1916
i= 1917
i= 1918
i= 1919
i= 1920
i= 1921
i= 1922
i= 1923
i= 1924
i= 1925
i= 1926
i= 1927
i= 1928
i= 1929
i= 1930
i= 1931
i= 1932
i= 1933
i= 1934
i= 1935
i= 1936
i= 1937
i= 1938
i= 1939
i= 1940
i= 1941
i= 1942
i= 1943
i= 1944
i= 1945
i= 1946
i= 1947
i= 1948
i= 1949
i= 1950
i= 1951
i= 1952
i= 1953
i= 1954
i= 1955
i= 1956
i= 1957
i= 1958
i= 1959
i= 1960
i= 1961
i= 1962
i= 1963
i= 1964
i= 1965
i= 1966
i= 1967
i= 1968
i= 1969
i= 1970
i= 1971
i= 1972
i= 1973
i= 1974
i= 1975
i= 1976
i= 1977
i= 1978
i= 1979
i= 1980
i= 1981
i= 1982
i= 1983
i= 1984
i= 1985
i= 1986
i= 1987
i= 1988
i= 1989
i= 1990
i= 1991
i= 1992
i= 1993
i= 1994
i= 1995
i= 1996
i= 1997
i= 1998
i= 1999
i= 2000
i= 2001
i= 2002
i= 2003
i= 2004
i= 2005
i= 2006
i= 2007
i= 2008
i= 2009
i= 2010
i= 2011
i= 2012
i= 2013
i= 2014
i= 2015
i= 2016
i= 2017
i= 2018
i= 2019
i= 2020
i= 2021
i= 2022
i= 2023
i= 2024
i= 2025
i= 2026
i= 2027
i= 2028
i= 2029
i= 2030
i= 2031
i= 2032
i= 2033
i= 2034
i= 2035
i= 2036
i= 2037
i= 2038
i= 2039
i= 2040
i= 2041
i= 2042
i= 2043
i= 2044
i= 2045
i= 2046
i= 2047
i= 2048
i= 2049
i= 2050
i= 2051
i= 2052
i= 2053
i= 2054
i= 2055
i= 2056
i= 2057
i= 2058
i= 2059
i= 2060
i= 2061
i= 2062
i= 2063
i= 2064
i= 2065
i= 2066
i= 2067
i= 2068
i= 2069
i= 2070
i= 2071
i= 2072
i= 2073
i= 2074
i= 2075
i= 2076
i= 2077
i= 2078
i= 2079
i= 2080
i= 2081
i= 2082
i= 2083
i= 2084
i= 2085
i= 2086
i= 2087
i= 2088
i= 2089
i= 2090
i= 2091
i= 2092
i= 2093
i= 2094
i= 2095
i= 2096
i= 2097
i= 2098
i= 2099
i= 2100
i= 2101
i= 2102
i= 2103
i= 2104
i= 2105
i= 2106
i= 2107
i= 2108
i= 2109
i= 2110
i= 2111
i= 2112
i= 2113
i= 2114
i= 2115
i= 2116
i= 2117
i= 2118
i= 2119
i= 2120
i= 2121
i= 2122
i= 2123
i= 2124
i= 2125
i= 2126
i= 2127
i= 2128
i= 2129
i= 2130
i= 2131
i= 2132
i= 2133
i= 2134
i= 2135
i= 2136
i= 2137
i= 2138
i= 2139
i= 2140
i= 2141
i= 2142
i= 2143
i= 2144
i= 2145
i= 2146
i= 2147
i= 2148
i= 2149
i= 2150
i= 2151
i= 2152
i= 2153
i= 2154
i= 2155
i= 2156
i= 2157
i= 2158
i= 2159
i= 2160
i= 2161
i= 2162
i= 2163
i= 2164
i= 2165
i= 2166
i= 2167
i= 2168
i= 2169
i= 2170
i= 2171
i= 2172
i= 2173
i= 2174
i= 2175
i= 2176
i= 2177
i= 2178
i= 2179
i= 2180
i= 2181
i= 2182
i= 2183
i= 2184
i= 2185
i= 2186
i= 2187
i= 2188

i= 2189
i= 2190
i= 2191
i= 2192
i= 2193
i= 2194
i= 2195
i= 2196
i= 2197
i= 2198
i= 2199
i= 2200
i= 2201
i= 2202
i= 2203
i= 2204
i= 2205
i= 2206
i= 2207
i= 2208
i= 2209
i= 2210
i= 2211
i= 2212
i= 2213
i= 2214
i= 2215
i= 2216
i= 2217
i= 2218
i= 2219
i= 2220
i= 2221
i= 2222
i= 2223
i= 2224
i= 2225
i= 2226
i= 2227
i= 2228
i= 2229
i= 2230
i= 2231
i= 2232
i= 2233
i= 2234
i= 2235
i= 2236
i= 2237
i= 2238
i= 2239
i= 2240
i= 2241
i= 2242
i= 2243
i= 2244
i= 2245
i= 2246
i= 2247
i= 2248
i= 2249
i= 2250
i= 2251
i= 2252
i= 2253
i= 2254
i= 2255
i= 2256
i= 2257
i= 2258
i= 2259
i= 2260
i= 2261
i= 2262
i= 2263
i= 2264
i= 2265
i= 2266
i= 2267
i= 2268
i= 2269
i= 2270
i= 2271
i= 2272
i= 2273
i= 2274
i= 2275
i= 2276
i= 2277
i= 2278
i= 2279
i= 2280
i= 2281
i= 2282
i= 2283
i= 2284
i= 2285
i= 2286
i= 2287
i= 2288
i= 2289
i= 2290
i= 2291
i= 2292
i= 2293
i= 2294
i= 2295
i= 2296
i= 2297
i= 2298
i= 2299
i= 2300
i= 2301
i= 2302
i= 2303
i= 2304
i= 2305
i= 2306
i= 2307
i= 2308
i= 2309
i= 2310
i= 2311
i= 2312
i= 2313
i= 2314
i= 2315
i= 2316
i= 2317
i= 2318
i= 2319
i= 2320
i= 2321
i= 2322
i= 2323
i= 2324
i= 2325
i= 2326
i= 2327
i= 2328
i= 2329
i= 2330
i= 2331
i= 2332
i= 2333
i= 2334
i= 2335
i= 2336
i= 2337
i= 2338
i= 2339
i= 2340
i= 2341
i= 2342
i= 2343
i= 2344
i= 2345
i= 2346
i= 2347
i= 2348
i= 2349
i= 2350
i= 2351
i= 2352
i= 2353
i= 2354
i= 2355
i= 2356
i= 2357
i= 2358
i= 2359
i= 2360
i= 2361
i= 2362
i= 2363
i= 2364
i= 2365
i= 2366
i= 2367
i= 2368
i= 2369
i= 2370
i= 2371
i= 2372
i= 2373
i= 2374
i= 2375
i= 2376
i= 2377
i= 2378
i= 2379
i= 2380
i= 2381
i= 2382
i= 2383
i= 2384
i= 2385
i= 2386
i= 2387
i= 2388
i= 2389
i= 2390
i= 2391
i= 2392
i= 2393
i= 2394
i= 2395
i= 2396
i= 2397
i= 2398
i= 2399
i= 2400
i= 2401
i= 2402
i= 2403
i= 2404
i= 2405
i= 2406
i= 2407
i= 2408
i= 2409
i= 2410
i= 2411
i= 2412
i= 2413
i= 2414
i= 2415
i= 2416
i= 2417
i= 2418
i= 2419
i= 2420
i= 2421
i= 2422
i= 2423
i= 2424
i= 2425
i= 2426
i= 2427
i= 2428
i= 2429
i= 2430
i= 2431
i= 2432
i= 2433
i= 2434
i= 2435
i= 2436
i= 2437
i= 2438
i= 2439
i= 2440
i= 2441
i= 2442
i= 2443
i= 2444
i= 2445
i= 2446
i= 2447
i= 2448
i= 2449
i= 2450
i= 2451
i= 2452
i= 2453
i= 2454
i= 2455
i= 2456
i= 2457
i= 2458
i= 2459
i= 2460
i= 2461
i= 2462
i= 2463
i= 2464
i= 2465
i= 2466
i= 2467
i= 2468
i= 2469
i= 2470
i= 2471
i= 2472
i= 2473
i= 2474
i= 2475
i= 2476
i= 2477
i= 2478
i= 2479
i= 2480
i= 2481
i= 2482
i= 2483
i= 2484
i= 2485
i= 2486
i= 2487
i= 2488
i= 2489
i= 2490
i= 2491
i= 2492
i= 2493
i= 2494
i= 2495
i= 2496
i= 2497
i= 2498
i= 2499
i= 2500
i= 2501
i= 2502
i= 2503
i= 2504
i= 2505
i= 2506
i= 2507
i= 2508
i= 2509
i= 2510
i= 2511
i= 2512
i= 2513
i= 2514
i= 2515
i= 2516
i= 2517
i= 2518
i= 2519
i= 2520
i= 2521
i= 2522
i= 2523
i= 2524
i= 2525
i= 2526
i= 2527
i= 2528
i= 2529
i= 2530
i= 2531
i= 2532
i= 2533
i= 2534
i= 2535
i= 2536
i= 2537
i= 2538
i= 2539
i= 2540
i= 2541
i= 2542
i= 2543
i= 2544
i= 2545
i= 2546
i= 2547
i= 2548
i= 2549
i= 2550
i= 2551
i= 2552
i= 2553
i= 2554
i= 2555
i= 2556
i= 2557
i= 2558
i= 2559
i= 2560
i= 2561
i= 2562
i= 2563
i= 2564
i= 2565
i= 2566
i= 2567
i= 2568
i= 2569
i= 2570
i= 2571
i= 2572
i= 2573
i= 2574
i= 2575
i= 2576
i= 2577
i= 2578
i= 2579
i= 2580
i= 2581
i= 2582
i= 2583
i= 2584
i= 2585
i= 2586
i= 2587
i= 2588
i= 2589
i= 2590
i= 2591
i= 2592
i= 2593
i= 2594
i= 2595
i= 2596
i= 2597
i= 2598
i= 2599
i= 2600
i= 2601
i= 2602
i= 2603
i= 2604
i= 2605
i= 2606
i= 2607
i= 2608
i= 2609
i= 2610
i= 2611
i= 2612
i= 2613
i= 2614
i= 2615
i= 2616
i= 2617
i= 2618
i= 2619
i= 2620
i= 2621
i= 2622
i= 2623
i= 2624
i= 2625
i= 2626
i= 2627
i= 2628
i= 2629
i= 2630
i= 2631
i= 2632
i= 2633
i= 2634
i= 2635
i= 2636
i= 2637
i= 2638
i= 2639
i= 2640
i= 2641
i= 2642
i= 2643
i= 2644
i= 2645
i= 2646
i= 2647
i= 2648
i= 2649
i= 2650
i= 2651
i= 2652
i= 2653
i= 2654
i= 2655
i= 2656
i= 2657
i= 2658
i= 2659
i= 2660
i= 2661
i= 2662
i= 2663
i= 2664
i= 2665
i= 2666
i= 2667
i= 2668
i= 2669
i= 2670
i= 2671
i= 2672
i= 2673
i= 2674
i= 2675
i= 2676
i= 2677
i= 2678
i= 2679
i= 2680
i= 2681
i= 2682
i= 2683
i= 2684
i= 2685
i= 2686
i= 2687
i= 2688
i= 2689
i= 2690
i= 2691
i= 2692
i= 2693
i= 2694
i= 2695
i= 2696
i= 2697
i= 2698
i= 2699
i= 2700
i= 2701
i= 2702
i= 2703
i= 2704
i= 2705
i= 2706
i= 2707
i= 2708
i= 2709
i= 2710
i= 2711
i= 2712
i= 2713
i= 2714
i= 2715
i= 2716
i= 2717
i= 2718
i= 2719
i= 2720
i= 2721
i= 2722
i= 2723
i= 2724
i= 2725
i= 2726
i= 2727
i= 2728
i= 2729
i= 2730
i= 2731
i= 2732
i= 2733
i= 2734
i= 2735
i= 2736
i= 2737
i= 2738
i= 2739
i= 2740
i= 2741
i= 2742
i= 2743
i= 2744
i= 2745
i= 2746
i= 2747
i= 2748
i= 2749
i= 2750
i= 2751
i= 2752
i= 2753
i= 2754
i= 2755
i= 2756
i= 2757
i= 2758
i= 2759
i= 2760
i= 2761
i= 2762
i= 2763
i= 2764
i= 2765
i= 2766
i= 2767
i= 2768
i= 2769
i= 2770
i= 2771
i= 2772
i= 2773
i= 2774
i= 2775
i= 2776
i= 2777
i= 2778
i= 2779
i= 2780
i= 2781
i= 2782
i= 2783
i= 2784
i= 2785
i= 2786
i= 2787
i= 2788
i= 2789
i= 2790
i= 2791
i= 2792
i= 2793
i= 2794
i= 2795
i= 2796
i= 2797
i= 2798
i= 2799
i= 2800
i= 2801
i= 2802
i= 2803
i= 2804
i= 2805
i= 2806
i= 2807
i= 2808
i= 2809
i= 2810
i= 2811
i= 2812
i= 2813
i= 2814
i= 2815
i= 2816
i= 2817
i= 2818
i= 2819
i= 2820
i= 2821
i= 2822
i= 2823
i= 2824
i= 2825
i= 2826
i= 2827
i= 2828
i= 2829
i= 2830
i= 2831
i= 2832
i= 2833
i= 2834
i= 2835
i= 2836
i= 2837
i= 2838
i= 2839
i= 2840
i= 2841
i= 2842
i= 2843
i= 2844
i= 2845
i= 2846
i= 2847
i= 2848
i= 2849
i= 2850
i= 2851
i= 2852
i= 2853
i= 2854
i= 2855
i= 2856
i= 2857
i= 2858
i= 2859
i= 2860
i= 2861
i= 2862
i= 2863
i= 2864
i= 2865
i= 2866
i= 2867
i= 2868
i= 2869
i= 2870
i= 2871
i= 2872
i= 2873
i= 2874
i= 2875
i= 2876
i= 2877
i= 2878
i= 2879
i= 2880
i= 2881
i= 2882
i= 2883
i= 2884
i= 2885
i= 2886
i= 2887
i= 2888
i= 2889
i= 2890
i= 2891
i= 2892
i= 2893
i= 2894
i= 2895
i= 2896
i= 2897
i= 2898
i= 2899
i= 2900
i= 2901
i= 2902
i= 2903
i= 2904
i= 2905
i= 2906
i= 2907
i= 2908
i= 2909
i= 2910
i= 2911
i= 2912
i= 2913
i= 2914
i= 2915
i= 2916
i= 2917
i= 2918
i= 2919
i= 2920
i= 2921
i= 2922
i= 2923
i= 2924
i= 2925
i= 2926
i= 2927
i= 2928
i= 2929
i= 2930
i= 2931
i= 2932
i= 2933
i= 2934
i= 2935
i= 2936
i= 2937
i= 2938
i= 2939
i= 2940
i= 2941
i= 2942
i= 2943
i= 2944
i= 2945
i= 2946
i= 2947
i= 2948
i= 2949
i= 2950
i= 2951
i= 2952
i= 2953
i= 2954
i= 2955
i= 2956
i= 2957
i= 2958
i= 2959
i= 2960
i= 2961
i= 2962
i= 2963
i= 2964
i= 2965
i= 2966
i= 2967
i= 2968
i= 2969
i= 2970
i= 2971
i= 2972
i= 2973
i= 2974
i= 2975
i= 2976
i= 2977
i= 2978
i= 2979
i= 2980
i= 2981
i= 2982
i= 2983
i= 2984
i= 2985
i= 2986
i= 2987
i= 2988
i= 2989
i= 2990
i= 2991
i= 2992
i= 2993
i= 2994
i= 2995
i= 2996
i= 2997
i= 2998
i= 2999
i= 3000
i= 3001
i= 3002
i= 3003
i= 3004
i= 3005
i= 3006
i= 3007
i= 3008
i= 3009
i= 3010
i= 3011
i= 3012
i= 3013
i= 3014
i= 3015
i= 3016
i= 3017
i= 3018
i= 3019
i= 3020
i= 3021
i= 3022
i= 3023
i= 3024
i= 3025
i= 3026
i= 3027
i= 3028
i= 3029
i= 3030
i= 3031
i= 3032
i= 3033
i= 3034
i= 3035
i= 3036
i= 3037
i= 3038
i= 3039
i= 3040
i= 3041
i= 3042
i= 3043
i= 3044
i= 3045
i= 3046
i= 3047
i= 3048
i= 3049
i= 3050
i= 3051
i= 3052
i= 3053
i= 3054
i= 3055
i= 3056
i= 3057
i= 3058
i= 3059
i= 3060
i= 3061
i= 3062
i= 3063
i= 3064
i= 3065
i= 3066
i= 3067
i= 3068
i= 3069
i= 3070
i= 3071
i= 3072
i= 3073
i= 3074
i= 3075
i= 3076
i= 3077
i= 3078
i= 3079
i= 3080
i= 3081
i= 3082
i= 3083
i= 3084
i= 3085
i= 3086
i= 3087
i= 3088
i= 3089
i= 3090
i= 3091
i= 3092
i= 3093
i= 3094
i= 3095
i= 3096
i= 3097
i= 3098
i= 3099
i= 3100
i= 3101
i= 3102
i= 3103
i= 3104
i= 3105
i= 3106
i= 3107
i= 3108
i= 3109
i= 3110
i= 3111
i= 3112
i= 3113
i= 3114
i= 3115
i= 3116
i= 3117
i= 3118
i= 3119
i= 3120
i= 3121
i= 3122
i= 3123
i= 3124
i= 3125
i= 3126
i= 3127
i= 3128
i= 3129
i= 3130
i= 3131
i= 3132
i= 3133
i= 3134
i= 3135
i= 3136
i= 3137
i= 3138
i= 3139
i= 3140
i= 3141
i= 3142
i= 3143
i= 3144
i= 3145
i= 3146
i= 3147
i= 3148
i= 3149
i= 3150
i= 3151
i= 3152
i= 3153
i= 3154
i= 3155
i= 3156
i= 3157
i= 3158
i= 3159
i= 3160
i= 3161
i= 3162
i= 3163
i= 3164
i= 3165
i= 3166
i= 3167
i= 3168
i= 3169
i= 3170
i= 3171
i= 3172
i= 3173
i= 3174
i= 3175
i= 3176
i= 3177
i= 3178
i= 3179
i= 3180
i= 3181
i= 3182
i= 3183
i= 3184
i= 3185
i= 3186
i= 3187
i= 3188
i= 3189
i= 3190
i= 3191
i= 3192
i= 3193
i= 3194
i= 3195
i= 3196
i= 3197
i= 3198
i= 3199
i= 3200
i= 3201
i= 3202
i= 3203
i= 3204
i= 3205
i= 3206
i= 3207
i= 3208
i= 3209
i= 3210
i= 3211
i= 3212
i= 3213
i= 3214

i= 3215
i= 3216
i= 3217
i= 3218
i= 3219
i= 3220
i= 3221
i= 3222
i= 3223
i= 3224
i= 3225
i= 3226
i= 3227
i= 3228
i= 3229
i= 3230
i= 3231
i= 3232
i= 3233
i= 3234
i= 3235
i= 3236
i= 3237
i= 3238
i= 3239
i= 3240
i= 3241
i= 3242
i= 3243
i= 3244
i= 3245
i= 3246
i= 3247
i= 3248
i= 3249
i= 3250
i= 3251
i= 3252
i= 3253
i= 3254
i= 3255
i= 3256
i= 3257
i= 3258
i= 3259
i= 3260
i= 3261
i= 3262
i= 3263
i= 3264
i= 3265
i= 3266
i= 3267
i= 3268
i= 3269
i= 3270
i= 3271
i= 3272
i= 3273
i= 3274
i= 3275
i= 3276
i= 3277
i= 3278
i= 3279
i= 3280
i= 3281
i= 3282
i= 3283
i= 3284
i= 3285
i= 3286
i= 3287
i= 3288
i= 3289
i= 3290
i= 3291
i= 3292
i= 3293
i= 3294
i= 3295
i= 3296
i= 3297
i= 3298
i= 3299
i= 3300
i= 3301
i= 3302
i= 3303
i= 3304
i= 3305
i= 3306
i= 3307
i= 3308
i= 3309
i= 3310
i= 3311
i= 3312
i= 3313
i= 3314
i= 3315
i= 3316
i= 3317
i= 3318
i= 3319
i= 3320
i= 3321
i= 3322
i= 3323
i= 3324
i= 3325
i= 3326
i= 3327
i= 3328
i= 3329
i= 3330
i= 3331
i= 3332
i= 3333
i= 3334
i= 3335
i= 3336
i= 3337
i= 3338
i= 3339
i= 3340
i= 3341
i= 3342
i= 3343
i= 3344
i= 3345
i= 3346
i= 3347
i= 3348
i= 3349
i= 3350
i= 3351
i= 3352
i= 3353
i= 3354
i= 3355
i= 3356
i= 3357
i= 3358
i= 3359
i= 3360
i= 3361
i= 3362
i= 3363
i= 3364
i= 3365
i= 3366
i= 3367
i= 3368
i= 3369
i= 3370
i= 3371
i= 3372
i= 3373
i= 3374
i= 3375
i= 3376
i= 3377
i= 3378
i= 3379
i= 3380
i= 3381
i= 3382
i= 3383
i= 3384
i= 3385
i= 3386
i= 3387
i= 3388
i= 3389
i= 3390
i= 3391
i= 3392
i= 3393
i= 3394
i= 3395
i= 3396
i= 3397
i= 3398
i= 3399
i= 3400
i= 3401
i= 3402
i= 3403
i= 3404
i= 3405
i= 3406
i= 3407
i= 3408
i= 3409
i= 3410
i= 3411
i= 3412
i= 3413
i= 3414
i= 3415
i= 3416
i= 3417
i= 3418
i= 3419
i= 3420
i= 3421
i= 3422
i= 3423
i= 3424
i= 3425
i= 3426
i= 3427
i= 3428
i= 3429
i= 3430
i= 3431
i= 3432
i= 3433
i= 3434
i= 3435
i= 3436
i= 3437
i= 3438
i= 3439
i= 3440
i= 3441
i= 3442
i= 3443
i= 3444
i= 3445
i= 3446
i= 3447
i= 3448
i= 3449
i= 3450
i= 3451
i= 3452
i= 3453
i= 3454
i= 3455
i= 3456
i= 3457
i= 3458
i= 3459
i= 3460
i= 3461
i= 3462
i= 3463
i= 3464
i= 3465
i= 3466
i= 3467
i= 3468
i= 3469
i= 3470
i= 3471
i= 3472
i= 3473
i= 3474
i= 3475
i= 3476
i= 3477
i= 3478
i= 3479
i= 3480
i= 3481
i= 3482
i= 3483
i= 3484
i= 3485
i= 3486
i= 3487
i= 3488
i= 3489
i= 3490
i= 3491
i= 3492
i= 3493
i= 3494
i= 3495
i= 3496
i= 3497
i= 3498
i= 3499
i= 3500
i= 3501
i= 3502
i= 3503
i= 3504
i= 3505
i= 3506
i= 3507
i= 3508
i= 3509
i= 3510
i= 3511
i= 3512
i= 3513
i= 3514
i= 3515
i= 3516
i= 3517
i= 3518
i= 3519
i= 3520
i= 3521
i= 3522
i= 3523
i= 3524
i= 3525
i= 3526
i= 3527
i= 3528
i= 3529
i= 3530
i= 3531
i= 3532
i= 3533
i= 3534
i= 3535
i= 3536
i= 3537
i= 3538
i= 3539
i= 3540
i= 3541
i= 3542
i= 3543
i= 3544
i= 3545
i= 3546
i= 3547
i= 3548
i= 3549
i= 3550
i= 3551
i= 3552
i= 3553
i= 3554
i= 3555
i= 3556
i= 3557
i= 3558
i= 3559
i= 3560
i= 3561
i= 3562
i= 3563
i= 3564
i= 3565
i= 3566
i= 3567
i= 3568
i= 3569
i= 3570
i= 3571
i= 3572
i= 3573
i= 3574
i= 3575
i= 3576
i= 3577
i= 3578
i= 3579
i= 3580
i= 3581
i= 3582
i= 3583
i= 3584
i= 3585
i= 3586
i= 3587
i= 3588
i= 3589
i= 3590
i= 3591
i= 3592
i= 3593
i= 3594
i= 3595
i= 3596
i= 3597
i= 3598
i= 3599
i= 3600
i= 3601
i= 3602
i= 3603
i= 3604
i= 3605
i= 3606
i= 3607
i= 3608
i= 3609
i= 3610
i= 3611
i= 3612
i= 3613
i= 3614
i= 3615
i= 3616
i= 3617
i= 3618
i= 3619
i= 3620
i= 3621
i= 3622
i= 3623
i= 3624
i= 3625
i= 3626
i= 3627
i= 3628
i= 3629
i= 3630
i= 3631
i= 3632
i= 3633
i= 3634
i= 3635
i= 3636
i= 3637
i= 3638
i= 3639
i= 3640
i= 3641
i= 3642
i= 3643
i= 3644
i= 3645
i= 3646
i= 3647
i= 3648
i= 3649
i= 3650
i= 3651
i= 3652
i= 3653
i= 3654
i= 3655
i= 3656
i= 3657
i= 3658
i= 3659
i= 3660
i= 3661
i= 3662
i= 3663
i= 3664
i= 3665
i= 3666
i= 3667
i= 3668
i= 3669
i= 3670
i= 3671
i= 3672
i= 3673
i= 3674
i= 3675
i= 3676
i= 3677
i= 3678
i= 3679
i= 3680
i= 3681
i= 3682
i= 3683
i= 3684
i= 3685
i= 3686
i= 3687
i= 3688
i= 3689
i= 3690
i= 3691
i= 3692
i= 3693
i= 3694
i= 3695
i= 3696
i= 3697
i= 3698
i= 3699
i= 3700
i= 3701
i= 3702
i= 3703
i= 3704
i= 3705
i= 3706
i= 3707
i= 3708
i= 3709
i= 3710
i= 3711
i= 3712
i= 3713
i= 3714
i= 3715
i= 3716
i= 3717
i= 3718
i= 3719
i= 3720
i= 3721
i= 3722
i= 3723
i= 3724
i= 3725
i= 3726
i= 3727
i= 3728
i= 3729
i= 3730
i= 3731
i= 3732
i= 3733
i= 3734
i= 3735
i= 3736
i= 3737
i= 3738
i= 3739
i= 3740
i= 3741
i= 3742
i= 3743
i= 3744
i= 3745
i= 3746
i= 3747
i= 3748
i= 3749
i= 3750
i= 3751
i= 3752
i= 3753
i= 3754
i= 3755
i= 3756
i= 3757
i= 3758
i= 3759
i= 3760
i= 3761
i= 3762
i= 3763
i= 3764
i= 3765
i= 3766
i= 3767
i= 3768
i= 3769
i= 3770
i= 3771
i= 3772
i= 3773
i= 3774
i= 3775
i= 3776
i= 3777
i= 3778
i= 3779
i= 3780
i= 3781
i= 3782
i= 3783
i= 3784
i= 3785
i= 3786
i= 3787
i= 3788
i= 3789
i= 3790
i= 3791
i= 3792
i= 3793
i= 3794
i= 3795
i= 3796
i= 3797
i= 3798
i= 3799
i= 3800
i= 3801
i= 3802
i= 3803
i= 3804
i= 3805
i= 3806
i= 3807
i= 3808
i= 3809
i= 3810
i= 3811
i= 3812
i= 3813
i= 3814
i= 3815
i= 3816
i= 3817
i= 3818
i= 3819
i= 3820
i= 3821
i= 3822
i= 3823
i= 3824
i= 3825
i= 3826
i= 3827
i= 3828
i= 3829
i= 3830
i= 3831
i= 3832
i= 3833
i= 3834
i= 3835
i= 3836
i= 3837
i= 3838
i= 3839
i= 3840
i= 3841
i= 3842
i= 3843
i= 3844
i= 3845
i= 3846
i= 3847
i= 3848
i= 3849
i= 3850
i= 3851
i= 3852
i= 3853
i= 3854
i= 3855
i= 3856
i= 3857
i= 3858
i= 3859
i= 3860
i= 3861
i= 3862
i= 3863
i= 3864
i= 3865
i= 3866
i= 3867
i= 3868
i= 3869
i= 3870
i= 3871
i= 3872
i= 3873
i= 3874
i= 3875
i= 3876
i= 3877
i= 3878
i= 3879
i= 3880
i= 3881
i= 3882
i= 3883
i= 3884
i= 3885
i= 3886
i= 3887
i= 3888
i= 3889
i= 3890
i= 3891
i= 3892
i= 3893
i= 3894
i= 3895
i= 3896
i= 3897
i= 3898
i= 3899
i= 3900
i= 3901
i= 3902
i= 3903
i= 3904
i= 3905
i= 3906
i= 3907
i= 3908
i= 3909
i= 3910
i= 3911
i= 3912
i= 3913
i= 3914
i= 3915
i= 3916
i= 3917
i= 3918
i= 3919
i= 3920
i= 3921
i= 3922
i= 3923
i= 3924
i= 3925
i= 3926
i= 3927
i= 3928
i= 3929
i= 3930
i= 3931
i= 3932
i= 3933
i= 3934
i= 3935
i= 3936
i= 3937
i= 3938
i= 3939
i= 3940
i= 3941
i= 3942
i= 3943
i= 3944
i= 3945
i= 3946
i= 3947
i= 3948
i= 3949
i= 3950
i= 3951
i= 3952
i= 3953
i= 3954
i= 3955
i= 3956
i= 3957
i= 3958
i= 3959
i= 3960
i= 3961
i= 3962
i= 3963
i= 3964
i= 3965
i= 3966
i= 3967
i= 3968
i= 3969
i= 3970
i= 3971
i= 3972
i= 3973
i= 3974
i= 3975
i= 3976
i= 3977
i= 3978
i= 3979
i= 3980
i= 3981
i= 3982
i= 3983
i= 3984
i= 3985
i= 3986
i= 3987
i= 3988
i= 3989
i= 3990
i= 3991
i= 3992
i= 3993
i= 3994
i= 3995
i= 3996
i= 3997
i= 3998
i= 3999
i= 4000
i= 4001
i= 4002
i= 4003
i= 4004
i= 4005
i= 4006
i= 4007
i= 4008
i= 4009
i= 4010
i= 4011
i= 4012
i= 4013
i= 4014
i= 4015
i= 4016
i= 4017
i= 4018
i= 4019
i= 4020
i= 4021
i= 4022
i= 4023
i= 4024
i= 4025
i= 4026
i= 4027
i= 4028
i= 4029
i= 4030
i= 4031
i= 4032
i= 4033
i= 4034
i= 4035
i= 4036
i= 4037
i= 4038
i= 4039
i= 4040
i= 4041
i= 4042
i= 4043
i= 4044
i= 4045
i= 4046
i= 4047
i= 4048
i= 4049
i= 4050
i= 4051
i= 4052
i= 4053
i= 4054
i= 4055
i= 4056
i= 4057
i= 4058
i= 4059
i= 4060
i= 4061
i= 4062
i= 4063
i= 4064
i= 4065
i= 4066
i= 4067
i= 4068
i= 4069
i= 4070
i= 4071
i= 4072
i= 4073
i= 4074
i= 4075
i= 4076
i= 4077
i= 4078
i= 4079
i= 4080
i= 4081
i= 4082
i= 4083
i= 4084
i= 4085
i= 4086
i= 4087
i= 4088
i= 4089
i= 4090
i= 4091
i= 4092
i= 4093
i= 4094
i= 4095
i= 4096
i= 4097
i= 4098
i= 4099
i= 4100
i= 4101
i= 4102
i= 4103
i= 4104
i= 4105
i= 4106
i= 4107
i= 4108
i= 4109
i= 4110
i= 4111
i= 4112
i= 4113
i= 4114
i= 4115
i= 4116
i= 4117
i= 4118
i= 4119
i= 4120
i= 4121
i= 4122
i= 4123
i= 4124
i= 4125
i= 4126
i= 4127
i= 4128
i= 4129
i= 4130
i= 4131
i= 4132
i= 4133
i= 4134
i= 4135
i= 4136
i= 4137
i= 4138
i= 4139
i= 4140
i= 4141
i= 4142
i= 4143
i= 4144
i= 4145
i= 4146
i= 4147
i= 4148
i= 4149
i= 4150
i= 4151
i= 4152
i= 4153
i= 4154
i= 4155
i= 4156
i= 4157
i= 4158
i= 4159
i= 4160
i= 4161
i= 4162
i= 4163
i= 4164
i= 4165
i= 4166
i= 4167
i= 4168
i= 4169
i= 4170
i= 4171
i= 4172
i= 4173
i= 4174
i= 4175
i= 4176
i= 4177
i= 4178
i= 4179
i= 4180
i= 4181
i= 4182
i= 4183
i= 4184
i= 4185
i= 4186
i= 4187
i= 4188
i= 4189
i= 4190
i= 4191
i= 4192
i= 4193
i= 4194
i= 4195
i= 4196
i= 4197
i= 4198
i= 4199
i= 4200
i= 4201
i= 4202
i= 4203
i= 4204
i= 4205
i= 4206
i= 4207
i= 4208
i= 4209
i= 4210
i= 4211
i= 4212
i= 4213
i= 4214
i= 4215
i= 4216
i= 4217
i= 4218
i= 4219
i= 4220
i= 4221
i= 4222
i= 4223
i= 4224
i= 4225
i= 4226
i= 4227
i= 4228
i= 4229
i= 4230
i= 4231
i= 4232
i= 4233
i= 4234
i= 4235
i= 4236
i= 4237
i= 4238
i= 4239
i= 4240

i= 4241
i= 4242
i= 4243
i= 4244
i= 4245
i= 4246
i= 4247
i= 4248
i= 4249
i= 4250
i= 4251
i= 4252
i= 4253
i= 4254
i= 4255
i= 4256
i= 4257
i= 4258
i= 4259
i= 4260
i= 4261
i= 4262
i= 4263
i= 4264
i= 4265
i= 4266
i= 4267
i= 4268
i= 4269
i= 4270
i= 4271
i= 4272
i= 4273
i= 4274
i= 4275
i= 4276
i= 4277
i= 4278
i= 4279
i= 4280
i= 4281
i= 4282
i= 4283
i= 4284
i= 4285
i= 4286
i= 4287
i= 4288
i= 4289
i= 4290
i= 4291
i= 4292
i= 4293
i= 4294
i= 4295
i= 4296
i= 4297
i= 4298
i= 4299
i= 4300
i= 4301
i= 4302
i= 4303
i= 4304
i= 4305
i= 4306
i= 4307
i= 4308
i= 4309
i= 4310
i= 4311
i= 4312
i= 4313
i= 4314
i= 4315
i= 4316
i= 4317
i= 4318
i= 4319
i= 4320
i= 4321
i= 4322
i= 4323
i= 4324
i= 4325
i= 4326
i= 4327
i= 4328
i= 4329
i= 4330
i= 4331
i= 4332
i= 4333
i= 4334
i= 4335
i= 4336
i= 4337
i= 4338
i= 4339
i= 4340
i= 4341
i= 4342
i= 4343
i= 4344
i= 4345
i= 4346
i= 4347
i= 4348
i= 4349
i= 4350
i= 4351
i= 4352
i= 4353
i= 4354
i= 4355
i= 4356
i= 4357
i= 4358
i= 4359
i= 4360
i= 4361
i= 4362
i= 4363
i= 4364
i= 4365
i= 4366
i= 4367
i= 4368
i= 4369
i= 4370
i= 4371
i= 4372
i= 4373
i= 4374
i= 4375
i= 4376
i= 4377
i= 4378
i= 4379
i= 4380
i= 4381
i= 4382
i= 4383
i= 4384
i= 4385
i= 4386
i= 4387
i= 4388
i= 4389
i= 4390
i= 4391
i= 4392
i= 4393
i= 4394
i= 4395
i= 4396
i= 4397
i= 4398
i= 4399
i= 4400
i= 4401
i= 4402
i= 4403
i= 4404
i= 4405
i= 4406
i= 4407
i= 4408
i= 4409
i= 4410
i= 4411
i= 4412
i= 4413
i= 4414
i= 4415
i= 4416
i= 4417
i= 4418
i= 4419
i= 4420
i= 4421
i= 4422
i= 4423
i= 4424
i= 4425
i= 4426
i= 4427
i= 4428
i= 4429
i= 4430
i= 4431
i= 4432
i= 4433
i= 4434
i= 4435
i= 4436
i= 4437
i= 4438
i= 4439
i= 4440
i= 4441
i= 4442
i= 4443
i= 4444
i= 4445
i= 4446
i= 4447
i= 4448
i= 4449
i= 4450
i= 4451
i= 4452
i= 4453
i= 4454
i= 4455
i= 4456
i= 4457
i= 4458
i= 4459
i= 4460
i= 4461
i= 4462
i= 4463
i= 4464
i= 4465
i= 4466
i= 4467
i= 4468
i= 4469
i= 4470
i= 4471
i= 4472
i= 4473
i= 4474
i= 4475
i= 4476
i= 4477
i= 4478
i= 4479
i= 4480
i= 4481
i= 4482
i= 4483
i= 4484
i= 4485
i= 4486
i= 4487
i= 4488
i= 4489
i= 4490
i= 4491
i= 4492
i= 4493
i= 4494
i= 4495
i= 4496
i= 4497
i= 4498
i= 4499
i= 4500
i= 4501
i= 4502
i= 4503
i= 4504
i= 4505
i= 4506
i= 4507
i= 4508
i= 4509
i= 4510
i= 4511
i= 4512
i= 4513
i= 4514
i= 4515
i= 4516
i= 4517
i= 4518
i= 4519
i= 4520
i= 4521
i= 4522
i= 4523
i= 4524
i= 4525
i= 4526
i= 4527
i= 4528
i= 4529
i= 4530
i= 4531
i= 4532
i= 4533
i= 4534
i= 4535
i= 4536
i= 4537
i= 4538
i= 4539
i= 4540
i= 4541
i= 4542
i= 4543
i= 4544
i= 4545
i= 4546
i= 4547
i= 4548
i= 4549
i= 4550
i= 4551
i= 4552
i= 4553
i= 4554
i= 4555
i= 4556
i= 4557
i= 4558
i= 4559
i= 4560
i= 4561
i= 4562
i= 4563
i= 4564
i= 4565
i= 4566
i= 4567
i= 4568
i= 4569
i= 4570
i= 4571
i= 4572
i= 4573
i= 4574
i= 4575
i= 4576
i= 4577
i= 4578
i= 4579
i= 4580
i= 4581
i= 4582
i= 4583
i= 4584
i= 4585
i= 4586
i= 4587
i= 4588
i= 4589
i= 4590
i= 4591
i= 4592
i= 4593
i= 4594
i= 4595
i= 4596
i= 4597
i= 4598
i= 4599
i= 4600
i= 4601
i= 4602
i= 4603
i= 4604
i= 4605
i= 4606
i= 4607
i= 4608
i= 4609
i= 4610
i= 4611
i= 4612
i= 4613
i= 4614
i= 4615
i= 4616
i= 4617
i= 4618
i= 4619
i= 4620
i= 4621
i= 4622
i= 4623
i= 4624
i= 4625
i= 4626
i= 4627
i= 4628
i= 4629
i= 4630
i= 4631
i= 4632
i= 4633
i= 4634
i= 4635
i= 4636
i= 4637
i= 4638
i= 4639
i= 4640
i= 4641
i= 4642
i= 4643
i= 4644
i= 4645
i= 4646
i= 4647
i= 4648
i= 4649
i= 4650
i= 4651
i= 4652
i= 4653
i= 4654
i= 4655
i= 4656
i= 4657
i= 4658
i= 4659
i= 4660
i= 4661
i= 4662
i= 4663
i= 4664
i= 4665
i= 4666
i= 4667
i= 4668
i= 4669
i= 4670
i= 4671
i= 4672
i= 4673
i= 4674
i= 4675
i= 4676
i= 4677
i= 4678
i= 4679
i= 4680
i= 4681
i= 4682
i= 4683
i= 4684
i= 4685
i= 4686
i= 4687
i= 4688
i= 4689
i= 4690
i= 4691
i= 4692
i= 4693
i= 4694
i= 4695
i= 4696
i= 4697
i= 4698
i= 4699
i= 4700
i= 4701
i= 4702
i= 4703
i= 4704
i= 4705
i= 4706
i= 4707
i= 4708
i= 4709
i= 4710
i= 4711
i= 4712
i= 4713
i= 4714
i= 4715
i= 4716
i= 4717
i= 4718
i= 4719
i= 4720
i= 4721
i= 4722
i= 4723
i= 4724
i= 4725
i= 4726
i= 4727
i= 4728
i= 4729
i= 4730
i= 4731
i= 4732
i= 4733
i= 4734
i= 4735
i= 4736
i= 4737
i= 4738
i= 4739
i= 4740
i= 4741
i= 4742
i= 4743
i= 4744
i= 4745
i= 4746
i= 4747
i= 4748
i= 4749
i= 4750
i= 4751
i= 4752
i= 4753
i= 4754
i= 4755
i= 4756
i= 4757
i= 4758
i= 4759
i= 4760
i= 4761
i= 4762
i= 4763
i= 4764
i= 4765
i= 4766
i= 4767
i= 4768
i= 4769
i= 4770
i= 4771
i= 4772
i= 4773
i= 4774
i= 4775
i= 4776
i= 4777
i= 4778
i= 4779
i= 4780
i= 4781
i= 4782
i= 4783
i= 4784
i= 4785
i= 4786
i= 4787
i= 4788
i= 4789
i= 4790
i= 4791
i= 4792
i= 4793
i= 4794
i= 4795
i= 4796
i= 4797
i= 4798
i= 4799
i= 4800
i= 4801
i= 4802

In [189]:
castNode[['cast_id','gender','id','order']] = castNode[['cast_id','gender','id','order']].astype(int)

In [327]:
castNode['category'] = 'Cast'

In [328]:
castNode.to_csv('castNode.csv',sep=',', header=True, index=False)

In [343]:
castNode

,cast_id,character,credit_id,gender,id,name,order,movie_id,category
0,242,Jake Sully,5602a8a7c3a3685532001c9a,2,65731,Sam Worthington,0,19995,Cast
1,3,Neytiri,52fe48009251416c750ac9cb,1,8691,Zoe Saldana,1,19995,Cast
2,25,Dr. Grace Augustine,52fe48009251416c750aca39,1,10205,Sigourney Weaver,2,19995,Cast
3,4,Col. Quaritch,52fe48009251416c750ac9cf,2,32747,Stephen Lang,3,19995,Cast
4,5,Trudy Chacon,52fe48009251416c750ac9d3,1,17647,Michelle Rodriguez,4,19995,Cast
5,8,Selfridge,52fe48009251416c750ac9e1,2,1771,Giovanni Ribisi,5,19995,Cast
6,7,Norm Spellman,52fe48009251416c750ac9dd,2,59231,Joel David Moore,6,19995,Cast
7,9,Moat,52fe48009251416c750ac9e5,1,30485,CCH Pounder,7,19995,Cast
8,11,Eytukan,52fe48009251416c750ac9ed,2,15853,Wes Studi,8,19995,Cast
9,10,Tsu'Tey,52fe48009251416c750ac9e9,2,10964,Laz Alonso,9,19995,Cast
10,12,Dr. Max Patel,52fe48009251416c750ac9f1,2,95697,Dileep Rao,10,19995,Cast
11,13,Lyle Wainfleet,52fe48009251416c750ac9f5,2,98215,Matt Gerald,11,19995,Cast
12,32,Private Fike,52fe48009251416c750aca5b,2,154153,Sean Anthony Moran,12,19995,Cast
13,33,Cryo Vault Med Tech,52fe48009251416c750aca5f,2,397312,Jason Whyte,13,19995,Cast
14,34,Venture Star Crew Chief,52fe48009251416c750aca63,2,42317,Scott Lawrence,14,19995,Cast
15,35,Lock Up Trooper,52fe48009251416c750aca67,2,986734,Kelly Kilgour,15,19995,Cast
16,36,Shuttle Pilot,52fe48009251416c750aca6b,0,1207227,James Patrick Pitt,16,19995,Cast
17,37,Shuttle Co-Pilot,52fe48009251416c750aca6f,0,1180936,Sean Patrick Murphy,17,19995,Cast
18,38,Shuttle Crew Chief,52fe48009251416c750aca73,2,1019578,Peter Dillon,18,19995,Cast
19,39,Tractor Operator / Troupe,52fe48009251416c750aca77,0,91443,Kevin Dorman,19,19995,Cast
20,40,Dragon Gunship Pilot,52fe48009251416c750aca7b,2,173391,Kelson Henderson,20,19995,Cast
21,41,Dragon Gunship Gunner,52fe48009251416c750aca7f,0,1207236,David Van Horn,21,19995,Cast
22,42,Dragon Gunship Navigator,52fe48009251416c750aca83,0,215913,Jacob Tomuri,22,19995,Cast
23,43,Suit #1,52fe48009251416c750aca87,0,143206,Michael Blain-Rozgay,23,19995,Cast
24,44,Suit #2,52fe48009251416c750aca8b,2,169676,Jon Curry,24,19995,Cast
25,46,Ambient Room Tech,52fe48009251416c750aca8f,0,1048610,Luke Hawker,25,19995,Cast
26,47,Ambient Room Tech / Troupe,52fe48009251416c750aca93,0,42288,Woody Schultz,26,19995,Cast
27,48,Horse Clan Leader,52fe48009251416c750aca97,2,68278,Peter Mensah,27,19995,Cast
28,49,Link Room Tech,52fe48009251416c750aca9b,0,1207247,Sonia Yee,28,19995,Cast
29,50,Basketball Avatar / Troupe,52fe48009251416c750aca9f,1,1207248,Jahnel Curfman,29,19995,Cast
...,...,...,...,...,...,...,...,...,...
2,4,Mauricio (Moco),52fe44eec3a36847f80b2805,2,57471,Peter Marquardt,3,9367,Cast
3,18,Azul,52fe44eec3a36847f80b2851,0,1192733,Reinol Martinez,4,9367,Cast
4,19,Cantinero,52fe44eec3a36847f80b2855,0,1192734,Ramiro Gomez,5,9367,Cast
5,20,Domino,5300df549251416ae738b1f4,0,1293343,Consuelo Gómez,6,9367,Cast
6,21,Moco's Men,58f41b409251413da7019f90,2,1066358,Juan García,7,9367,Cast
0,1,Buzzy,52fe487dc3a368484e0fb001,2,12833,Edward Burns,0,72766,Cast
1,2,Linda,52fe487dc3a368484e0fb005,1,58356,Kerry Bishé,1,72766,Cast
2,3,Marsha,52fe487dc3a368484e0fb009,1,17188,Marsha Dietlein,2,72766,Cast
3,4,Katie,52fe487dc3a368484e0fb00d,1,211993,Caitlin Fitzgerald,3,72766,Cast
4,7,Vanessa,52fe487dc3a368484e0fb01d,0,1257819,Daniella Pineda,4,72766,Cast
0,8,Oliver O’Toole,52fe4df3c3a36847f8275ed3,2,11867,Eric Mabius,0,231617,Cast
1,9,Shane McInerney,52fe4df3c3a36847f8275ed7,1,34915,Kristin Booth,1,231617,Cast
2,11,Rita Haywith,52fe4df3c3a36847f8275edf,1,58393,Crystal Lowe,2,231617,Cast
3,12,Norman Dorman,52fe4df3c3a36847f8275ee3,0,119810,Geoff Gustafson,3,231617,Cast
4,14,Charlie Riggs,52fe4df3c3a36847f8275eeb,2,77865,Benjamin Hollingsworth,4,231617,Cast
5,13,Kelly,52fe4df3c3a36847f8275ee7,1,1037844,Laci J Mailey,5,231617,Cast
6,10,Andrea Shmeckle,52fe4df3c3a36847f8275edb,1,14668,Daphne Zuniga,6,231617,Cast
0,3,Sam,52fe4ad9c3a368484e16a375,2,82093,Daniel Henney,0,126186,Cast
1,4,Amanda,52fe4ad9c3a368484e16a379,1,210050,Eliza Coupe,1,126186,Cast
2,5,Donald,52fe4ad9c3a368484e16a37d,2,2053,Bill Paxton,2,126186,Cast
3,6,Marcus Groff,52fe4ad9c3a368484e16a381,2,2394,Alan Ruck,3,126186,Cast
4,7,,548347219251416e7b0081f7,0,1395490,Zhu Shimao,4,126186,Cast
0,3,Herself,52fe44e8c3a368484e03da91,1,69597,Drew Barrymore,0,25975,Cast
1,5,Himself,58ce01169251415a3901648f,2,85563,Brian Herzlinger,1,25975,Cast
2,6,Himself,58ce01339251415a410167f0,2,3034,Corey Feldman,2,25975,Cast
3,8,Himself,58ce018c9251415a7d016e36,2,21315,Eric Roberts,3,25975,Cast
4,9,Himself,58ce01b99251415a7d016e7d,0,2171,Griffin Dunne,4,25975,Cast
5,10,Himself,58ce01d19251415a8b0168be,2,2231,Samuel L. Jackson,5,25975,Cast
6,11,Himself,58ce01dd9251415a39016580,2,14407,Matt LeBlanc,6,25975,Cast
7,7,Himself,58ce0164c3a3685104015b28,2,155007,Bill D'Elia,7,25975,Cast

In [405]:
#简单、合并版castNode
castNode1 = castNode.drop(['cast_id','character','credit_id','order'],axis=1,inplace=False)

In [406]:
castNode1.head()

   gender     id                name  movie_id category
0       2  65731     Sam Worthington     19995     Cast
1       1   8691         Zoe Saldana     19995     Cast
2       1  10205    Sigourney Weaver     19995     Cast
3       2  32747        Stephen Lang     19995     Cast
4       1  17647  Michelle Rodriguez     19995     Cast

In [407]:
castNode1[['movie_id']] = castNode1[['movie_id']].astype(str)

In [408]:
# 按name合并多行

def ab(df):
    return','.join(df.values)

def simplify(x):
    line = x.split(',')
    return ','.join(list(set(line)))

In [409]:
castNode1 = castNode1.groupby(['id','name','gender'])['movie_id'].apply(ab)
castNode1 = castNode1.reset_index()

In [410]:
castNode1['movie_id'] = castNode1['movie_id'].apply(lambda x: simplify(x))

In [411]:
castNode1['category'] = 'Cast'

In [412]:
castNode1.head(2)

   id          name  gender           movie_id category
0   1  George Lucas       2    87,879,306,1895     Cast
1   2   Mark Hamill       2  1892,2294,1891,11     Cast

In [413]:
castNode1.to_csv('castNode_simplified.csv',sep=',', header=True, index=False)

In [ ]:
# CrewNode

In [195]:
mov['crew'][0][0]

{'credit_id': '52fe48009251416c750aca23',
 'department': 'Editing',
 'gender': 0,
 'id': 1721,
 'job': 'Editor',
 'name': 'Stephen E. Rivkin'}

In [220]:
crewNode = pd.DataFrame(data = mov['crew'][0])
colname4 = crewNode.columns.tolist()
colname4.insert(7,'movie_id')
crewNode = crewNode.reindex(columns=colname4)
crewNode['movie_id'] = movies['id'][0]

In [221]:
for i in range(1,4803):
    tempNode1 = pd.DataFrame(data = mov['crew'][i])
    tempNode1 = tempNode1.reindex(columns=colname4)
    tempNode1['movie_id'] = movies['id'][i]
    crewNode = crewNode.append(tempNode1)
    print("i=",i)

i= 1
i= 2
i= 3
i= 4
i= 5
i= 6
i= 7
i= 8
i= 9
i= 10
i= 11
i= 12
i= 13
i= 14
i= 15
i= 16
i= 17
i= 18
i= 19
i= 20
i= 21
i= 22
i= 23
i= 24
i= 25
i= 26
i= 27
i= 28
i= 29
i= 30
i= 31
i= 32
i= 33
i= 34
i= 35
i= 36
i= 37
i= 38
i= 39
i= 40
i= 41
i= 42
i= 43
i= 44
i= 45
i= 46
i= 47
i= 48
i= 49
i= 50
i= 51
i= 52
i= 53
i= 54
i= 55
i= 56
i= 57
i= 58
i= 59
i= 60
i= 61
i= 62
i= 63
i= 64
i= 65
i= 66
i= 67
i= 68
i= 69
i= 70
i= 71
i= 72
i= 73
i= 74
i= 75
i= 76
i= 77
i= 78
i= 79
i= 80
i= 81
i= 82
i= 83
i= 84
i= 85
i= 86
i= 87
i= 88
i= 89
i= 90
i= 91
i= 92
i= 93
i= 94
i= 95
i= 96
i= 97
i= 98
i= 99
i= 100
i= 101
i= 102
i= 103
i= 104
i= 105
i= 106
i= 107
i= 108
i= 109
i= 110
i= 111
i= 112
i= 113
i= 114
i= 115
i= 116
i= 117
i= 118
i= 119
i= 120
i= 121
i= 122
i= 123
i= 124
i= 125
i= 126
i= 127
i= 128
i= 129
i= 130
i= 131
i= 132
i= 133
i= 134
i= 135
i= 136
i= 137
i= 138
i= 139
i= 140
i= 141
i= 142
i= 143
i= 144
i= 145
i= 146
i= 147
i= 148
i= 149
i= 150
i= 151
i= 152
i= 153
i= 154
i= 155
i= 156
i= 157
i= 158
i= 159
i= 160
i= 161
i= 162
i= 163
i= 164
i= 165
i= 166
i= 167
i= 168
i= 169
i= 170
i= 171
i= 172
i= 173
i= 174
i= 175
i= 176
i= 177
i= 178
i= 179
i= 180
i= 181
i= 182
i= 183
i= 184
i= 185
i= 186
i= 187
i= 188
i= 189
i= 190
i= 191
i= 192
i= 193
i= 194
i= 195
i= 196
i= 197
i= 198
i= 199
i= 200
i= 201
i= 202
i= 203
i= 204
i= 205
i= 206
i= 207
i= 208
i= 209
i= 210
i= 211
i= 212
i= 213
i= 214
i= 215
i= 216
i= 217
i= 218
i= 219
i= 220
i= 221
i= 222
i= 223
i= 224
i= 225
i= 226
i= 227
i= 228
i= 229
i= 230
i= 231
i= 232
i= 233
i= 234
i= 235
i= 236
i= 237
i= 238
i= 239
i= 240
i= 241
i= 242
i= 243
i= 244
i= 245
i= 246
i= 247
i= 248
i= 249
i= 250
i= 251
i= 252
i= 253
i= 254
i= 255
i= 256
i= 257
i= 258
i= 259
i= 260
i= 261
i= 262
i= 263
i= 264
i= 265
i= 266
i= 267
i= 268
i= 269
i= 270
i= 271
i= 272
i= 273
i= 274
i= 275
i= 276
i= 277
i= 278
i= 279
i= 280
i= 281
i= 282
i= 283
i= 284
i= 285
i= 286
i= 287
i= 288
i= 289
i= 290
i= 291
i= 292
i= 293
i= 294
i= 295
i= 296
i= 297
i= 298
i= 299
i= 300
i= 301
i= 302
i= 303
i= 304
i= 305
i= 306
i= 307
i= 308
i= 309
i= 310
i= 311
i= 312
i= 313
i= 314
i= 315
i= 316
i= 317
i= 318
i= 319
i= 320
i= 321
i= 322
i= 323
i= 324
i= 325
i= 326
i= 327
i= 328
i= 329
i= 330
i= 331
i= 332
i= 333
i= 334
i= 335
i= 336
i= 337
i= 338
i= 339
i= 340
i= 341
i= 342
i= 343
i= 344
i= 345
i= 346
i= 347
i= 348
i= 349
i= 350
i= 351
i= 352
i= 353
i= 354
i= 355
i= 356
i= 357
i= 358
i= 359
i= 360
i= 361
i= 362
i= 363
i= 364
i= 365
i= 366
i= 367
i= 368
i= 369
i= 370
i= 371
i= 372
i= 373
i= 374
i= 375
i= 376
i= 377
i= 378
i= 379
i= 380
i= 381
i= 382
i= 383
i= 384
i= 385
i= 386
i= 387
i= 388
i= 389
i= 390
i= 391
i= 392
i= 393
i= 394
i= 395
i= 396
i= 397
i= 398
i= 399
i= 400
i= 401
i= 402
i= 403
i= 404
i= 405
i= 406
i= 407
i= 408
i= 409
i= 410
i= 411
i= 412
i= 413
i= 414
i= 415
i= 416
i= 417
i= 418
i= 419
i= 420
i= 421
i= 422
i= 423
i= 424
i= 425
i= 426
i= 427
i= 428
i= 429
i= 430
i= 431
i= 432
i= 433
i= 434
i= 435
i= 436
i= 437
i= 438
i= 439
i= 440
i= 441
i= 442
i= 443
i= 444
i= 445
i= 446
i= 447
i= 448
i= 449
i= 450
i= 451
i= 452
i= 453
i= 454
i= 455
i= 456
i= 457
i= 458
i= 459
i= 460
i= 461
i= 462
i= 463
i= 464
i= 465
i= 466
i= 467
i= 468
i= 469
i= 470
i= 471
i= 472
i= 473
i= 474
i= 475
i= 476
i= 477
i= 478
i= 479
i= 480
i= 481
i= 482
i= 483
i= 484
i= 485
i= 486
i= 487
i= 488
i= 489
i= 490
i= 491
i= 492
i= 493
i= 494
i= 495
i= 496
i= 497
i= 498
i= 499
i= 500
i= 501
i= 502
i= 503
i= 504
i= 505
i= 506
i= 507
i= 508
i= 509
i= 510
i= 511
i= 512
i= 513
i= 514
i= 515
i= 516
i= 517
i= 518
i= 519
i= 520
i= 521
i= 522
i= 523
i= 524
i= 525
i= 526
i= 527
i= 528
i= 529
i= 530
i= 531
i= 532
i= 533
i= 534
i= 535
i= 536
i= 537
i= 538
i= 539
i= 540
i= 541
i= 542
i= 543
i= 544
i= 545
i= 546
i= 547
i= 548
i= 549
i= 550
i= 551
i= 552
i= 553
i= 554
i= 555
i= 556
i= 557
i= 558
i= 559
i= 560
i= 561
i= 562
i= 563
i= 564
i= 565
i= 566
i= 567
i= 568
i= 569
i= 570
i= 571
i= 572
i= 573
i= 574
i= 575
i= 576
i= 577
i= 578
i= 579
i= 580
i= 581
i= 582
i= 583
i= 584
i= 585
i= 586
i= 587
i= 588
i= 589
i= 590
i= 591
i= 592
i= 593
i= 594
i= 595
i= 596
i= 597
i= 598
i= 599
i= 600
i= 601
i= 602
i= 603
i= 604
i= 605
i= 606
i= 607
i= 608
i= 609
i= 610
i= 611
i= 612
i= 613
i= 614
i= 615
i= 616
i= 617
i= 618
i= 619
i= 620
i= 621
i= 622
i= 623
i= 624
i= 625
i= 626
i= 627
i= 628
i= 629
i= 630
i= 631
i= 632
i= 633
i= 634
i= 635
i= 636
i= 637
i= 638
i= 639
i= 640
i= 641
i= 642
i= 643
i= 644
i= 645
i= 646
i= 647
i= 648
i= 649
i= 650
i= 651
i= 652
i= 653
i= 654
i= 655
i= 656
i= 657
i= 658
i= 659
i= 660
i= 661
i= 662
i= 663
i= 664
i= 665
i= 666
i= 667
i= 668
i= 669
i= 670
i= 671
i= 672
i= 673
i= 674
i= 675
i= 676
i= 677
i= 678
i= 679
i= 680
i= 681
i= 682
i= 683
i= 684
i= 685
i= 686
i= 687
i= 688
i= 689
i= 690
i= 691
i= 692
i= 693
i= 694
i= 695
i= 696
i= 697
i= 698
i= 699
i= 700
i= 701
i= 702
i= 703
i= 704
i= 705
i= 706
i= 707
i= 708
i= 709
i= 710
i= 711
i= 712
i= 713
i= 714
i= 715
i= 716
i= 717
i= 718
i= 719
i= 720
i= 721
i= 722
i= 723
i= 724
i= 725
i= 726
i= 727
i= 728
i= 729
i= 730
i= 731
i= 732
i= 733
i= 734
i= 735
i= 736
i= 737
i= 738
i= 739
i= 740
i= 741
i= 742
i= 743
i= 744
i= 745
i= 746
i= 747
i= 748
i= 749
i= 750
i= 751
i= 752
i= 753
i= 754
i= 755
i= 756
i= 757
i= 758
i= 759
i= 760
i= 761
i= 762
i= 763
i= 764
i= 765
i= 766
i= 767
i= 768
i= 769
i= 770
i= 771
i= 772
i= 773
i= 774
i= 775
i= 776
i= 777
i= 778
i= 779
i= 780
i= 781
i= 782
i= 783
i= 784
i= 785
i= 786
i= 787
i= 788
i= 789
i= 790
i= 791
i= 792
i= 793
i= 794
i= 795
i= 796
i= 797
i= 798
i= 799
i= 800
i= 801
i= 802
i= 803
i= 804
i= 805
i= 806
i= 807
i= 808
i= 809
i= 810
i= 811
i= 812
i= 813
i= 814
i= 815
i= 816
i= 817
i= 818
i= 819
i= 820
i= 821
i= 822
i= 823
i= 824
i= 825
i= 826
i= 827
i= 828
i= 829
i= 830
i= 831
i= 832
i= 833
i= 834
i= 835
i= 836
i= 837
i= 838
i= 839
i= 840
i= 841
i= 842
i= 843
i= 844
i= 845
i= 846
i= 847
i= 848
i= 849
i= 850
i= 851
i= 852
i= 853
i= 854
i= 855
i= 856
i= 857
i= 858
i= 859
i= 860
i= 861
i= 862
i= 863
i= 864
i= 865
i= 866
i= 867
i= 868
i= 869
i= 870
i= 871
i= 872
i= 873
i= 874
i= 875
i= 876
i= 877
i= 878
i= 879
i= 880
i= 881
i= 882
i= 883
i= 884
i= 885
i= 886
i= 887
i= 888
i= 889
i= 890
i= 891
i= 892
i= 893
i= 894
i= 895
i= 896
i= 897
i= 898
i= 899
i= 900
i= 901
i= 902
i= 903
i= 904
i= 905
i= 906
i= 907
i= 908
i= 909
i= 910
i= 911
i= 912
i= 913
i= 914
i= 915
i= 916
i= 917
i= 918
i= 919
i= 920
i= 921
i= 922
i= 923
i= 924
i= 925
i= 926
i= 927
i= 928
i= 929
i= 930
i= 931
i= 932
i= 933
i= 934
i= 935
i= 936
i= 937
i= 938
i= 939
i= 940
i= 941
i= 942
i= 943
i= 944
i= 945
i= 946
i= 947
i= 948
i= 949
i= 950
i= 951
i= 952
i= 953
i= 954
i= 955
i= 956
i= 957
i= 958
i= 959
i= 960
i= 961
i= 962
i= 963
i= 964
i= 965
i= 966
i= 967
i= 968
i= 969
i= 970
i= 971
i= 972
i= 973
i= 974
i= 975
i= 976
i= 977
i= 978
i= 979
i= 980
i= 981
i= 982
i= 983
i= 984
i= 985
i= 986
i= 987
i= 988
i= 989
i= 990
i= 991
i= 992
i= 993
i= 994
i= 995
i= 996
i= 997
i= 998
i= 999
i= 1000
i= 1001
i= 1002
i= 1003
i= 1004
i= 1005
i= 1006
i= 1007
i= 1008
i= 1009
i= 1010
i= 1011
i= 1012
i= 1013
i= 1014
i= 1015
i= 1016
i= 1017
i= 1018
i= 1019
i= 1020
i= 1021
i= 1022
i= 1023
i= 1024
i= 1025
i= 1026
i= 1027
i= 1028
i= 1029
i= 1030
i= 1031
i= 1032
i= 1033
i= 1034
i= 1035
i= 1036
i= 1037
i= 1038
i= 1039
i= 1040
i= 1041
i= 1042
i= 1043
i= 1044
i= 1045
i= 1046
i= 1047
i= 1048
i= 1049
i= 1050
i= 1051
i= 1052
i= 1053
i= 1054
i= 1055
i= 1056
i= 1057
i= 1058
i= 1059
i= 1060
i= 1061
i= 1062
i= 1063
i= 1064
i= 1065
i= 1066
i= 1067
i= 1068
i= 1069
i= 1070
i= 1071
i= 1072
i= 1073
i= 1074
i= 1075
i= 1076
i= 1077
i= 1078
i= 1079
i= 1080
i= 1081
i= 1082
i= 1083
i= 1084
i= 1085
i= 1086
i= 1087
i= 1088
i= 1089
i= 1090
i= 1091
i= 1092
i= 1093
i= 1094
i= 1095
i= 1096
i= 1097
i= 1098
i= 1099
i= 1100
i= 1101
i= 1102
i= 1103
i= 1104
i= 1105
i= 1106
i= 1107
i= 1108
i= 1109
i= 1110
i= 1111
i= 1112
i= 1113
i= 1114
i= 1115
i= 1116
i= 1117
i= 1118
i= 1119
i= 1120
i= 1121
i= 1122
i= 1123
i= 1124
i= 1125
i= 1126
i= 1127
i= 1128
i= 1129
i= 1130
i= 1131
i= 1132
i= 1133
i= 1134
i= 1135
i= 1136
i= 1137
i= 1138
i= 1139
i= 1140
i= 1141
i= 1142
i= 1143
i= 1144
i= 1145
i= 1146
i= 1147
i= 1148
i= 1149
i= 1150
i= 1151
i= 1152
i= 1153
i= 1154
i= 1155
i= 1156
i= 1157
i= 1158
i= 1159
i= 1160
i= 1161
i= 1162
i= 1163
i= 1164
i= 1165
i= 1166

i= 1167
i= 1168
i= 1169
i= 1170
i= 1171
i= 1172
i= 1173
i= 1174
i= 1175
i= 1176
i= 1177
i= 1178
i= 1179
i= 1180
i= 1181
i= 1182
i= 1183
i= 1184
i= 1185
i= 1186
i= 1187
i= 1188
i= 1189
i= 1190
i= 1191
i= 1192
i= 1193
i= 1194
i= 1195
i= 1196
i= 1197
i= 1198
i= 1199
i= 1200
i= 1201
i= 1202
i= 1203
i= 1204
i= 1205
i= 1206
i= 1207
i= 1208
i= 1209
i= 1210
i= 1211
i= 1212
i= 1213
i= 1214
i= 1215
i= 1216
i= 1217
i= 1218
i= 1219
i= 1220
i= 1221
i= 1222
i= 1223
i= 1224
i= 1225
i= 1226
i= 1227
i= 1228
i= 1229
i= 1230
i= 1231
i= 1232
i= 1233
i= 1234
i= 1235
i= 1236
i= 1237
i= 1238
i= 1239
i= 1240
i= 1241
i= 1242
i= 1243
i= 1244
i= 1245
i= 1246
i= 1247
i= 1248
i= 1249
i= 1250
i= 1251
i= 1252
i= 1253
i= 1254
i= 1255
i= 1256
i= 1257
i= 1258
i= 1259
i= 1260
i= 1261
i= 1262
i= 1263
i= 1264
i= 1265
i= 1266
i= 1267
i= 1268
i= 1269
i= 1270
i= 1271
i= 1272
i= 1273
i= 1274
i= 1275
i= 1276
i= 1277
i= 1278
i= 1279
i= 1280
i= 1281
i= 1282
i= 1283
i= 1284
i= 1285
i= 1286
i= 1287
i= 1288
i= 1289
i= 1290
i= 1291
i= 1292
i= 1293
i= 1294
i= 1295
i= 1296
i= 1297
i= 1298
i= 1299
i= 1300
i= 1301
i= 1302
i= 1303
i= 1304
i= 1305
i= 1306
i= 1307
i= 1308
i= 1309
i= 1310
i= 1311
i= 1312
i= 1313
i= 1314
i= 1315
i= 1316
i= 1317
i= 1318
i= 1319
i= 1320
i= 1321
i= 1322
i= 1323
i= 1324
i= 1325
i= 1326
i= 1327
i= 1328
i= 1329
i= 1330
i= 1331
i= 1332
i= 1333
i= 1334
i= 1335
i= 1336
i= 1337
i= 1338
i= 1339
i= 1340
i= 1341
i= 1342
i= 1343
i= 1344
i= 1345
i= 1346
i= 1347
i= 1348
i= 1349
i= 1350
i= 1351
i= 1352
i= 1353
i= 1354
i= 1355
i= 1356
i= 1357
i= 1358
i= 1359
i= 1360
i= 1361
i= 1362
i= 1363
i= 1364
i= 1365
i= 1366
i= 1367
i= 1368
i= 1369
i= 1370
i= 1371
i= 1372
i= 1373
i= 1374
i= 1375
i= 1376
i= 1377
i= 1378
i= 1379
i= 1380
i= 1381
i= 1382
i= 1383
i= 1384
i= 1385
i= 1386
i= 1387
i= 1388
i= 1389
i= 1390
i= 1391
i= 1392
i= 1393
i= 1394
i= 1395
i= 1396
i= 1397
i= 1398
i= 1399
i= 1400
i= 1401
i= 1402
i= 1403
i= 1404
i= 1405
i= 1406
i= 1407
i= 1408
i= 1409
i= 1410
i= 1411
i= 1412
i= 1413
i= 1414
i= 1415
i= 1416
i= 1417
i= 1418
i= 1419
i= 1420
i= 1421
i= 1422
i= 1423
i= 1424
i= 1425
i= 1426
i= 1427
i= 1428
i= 1429
i= 1430
i= 1431
i= 1432
i= 1433
i= 1434
i= 1435
i= 1436
i= 1437
i= 1438
i= 1439
i= 1440
i= 1441
i= 1442
i= 1443
i= 1444
i= 1445
i= 1446
i= 1447
i= 1448
i= 1449
i= 1450
i= 1451
i= 1452
i= 1453
i= 1454
i= 1455
i= 1456
i= 1457
i= 1458
i= 1459
i= 1460
i= 1461
i= 1462
i= 1463
i= 1464
i= 1465
i= 1466
i= 1467
i= 1468
i= 1469
i= 1470
i= 1471
i= 1472
i= 1473
i= 1474
i= 1475
i= 1476
i= 1477
i= 1478
i= 1479
i= 1480
i= 1481
i= 1482
i= 1483
i= 1484
i= 1485
i= 1486
i= 1487
i= 1488
i= 1489
i= 1490
i= 1491
i= 1492
i= 1493
i= 1494
i= 1495
i= 1496
i= 1497
i= 1498
i= 1499
i= 1500
i= 1501
i= 1502
i= 1503
i= 1504
i= 1505
i= 1506
i= 1507
i= 1508
i= 1509
i= 1510
i= 1511
i= 1512
i= 1513
i= 1514
i= 1515
i= 1516
i= 1517
i= 1518
i= 1519
i= 1520
i= 1521
i= 1522
i= 1523
i= 1524
i= 1525
i= 1526
i= 1527
i= 1528
i= 1529
i= 1530
i= 1531
i= 1532
i= 1533
i= 1534
i= 1535
i= 1536
i= 1537
i= 1538
i= 1539
i= 1540
i= 1541
i= 1542
i= 1543
i= 1544
i= 1545
i= 1546
i= 1547
i= 1548
i= 1549
i= 1550
i= 1551
i= 1552
i= 1553
i= 1554
i= 1555
i= 1556
i= 1557
i= 1558
i= 1559
i= 1560
i= 1561
i= 1562
i= 1563
i= 1564
i= 1565
i= 1566
i= 1567
i= 1568
i= 1569
i= 1570
i= 1571
i= 1572
i= 1573
i= 1574
i= 1575
i= 1576
i= 1577
i= 1578
i= 1579
i= 1580
i= 1581
i= 1582
i= 1583
i= 1584
i= 1585
i= 1586
i= 1587
i= 1588
i= 1589
i= 1590
i= 1591
i= 1592
i= 1593
i= 1594
i= 1595
i= 1596
i= 1597
i= 1598
i= 1599
i= 1600
i= 1601
i= 1602
i= 1603
i= 1604
i= 1605
i= 1606
i= 1607
i= 1608
i= 1609
i= 1610
i= 1611
i= 1612
i= 1613
i= 1614
i= 1615
i= 1616
i= 1617
i= 1618
i= 1619
i= 1620
i= 1621
i= 1622
i= 1623
i= 1624
i= 1625
i= 1626
i= 1627
i= 1628
i= 1629
i= 1630
i= 1631
i= 1632
i= 1633
i= 1634
i= 1635
i= 1636
i= 1637
i= 1638
i= 1639
i= 1640
i= 1641
i= 1642
i= 1643
i= 1644
i= 1645
i= 1646
i= 1647
i= 1648
i= 1649
i= 1650
i= 1651
i= 1652
i= 1653
i= 1654
i= 1655
i= 1656
i= 1657
i= 1658
i= 1659
i= 1660
i= 1661
i= 1662
i= 1663
i= 1664
i= 1665
i= 1666
i= 1667
i= 1668
i= 1669
i= 1670
i= 1671
i= 1672
i= 1673
i= 1674
i= 1675
i= 1676
i= 1677
i= 1678
i= 1679
i= 1680
i= 1681
i= 1682
i= 1683
i= 1684
i= 1685
i= 1686
i= 1687
i= 1688
i= 1689
i= 1690
i= 1691
i= 1692
i= 1693
i= 1694
i= 1695
i= 1696
i= 1697
i= 1698
i= 1699
i= 1700
i= 1701
i= 1702
i= 1703
i= 1704
i= 1705
i= 1706
i= 1707
i= 1708
i= 1709
i= 1710
i= 1711
i= 1712
i= 1713
i= 1714
i= 1715
i= 1716
i= 1717
i= 1718
i= 1719
i= 1720
i= 1721
i= 1722
i= 1723
i= 1724
i= 1725
i= 1726
i= 1727
i= 1728
i= 1729
i= 1730
i= 1731
i= 1732
i= 1733
i= 1734
i= 1735
i= 1736
i= 1737
i= 1738
i= 1739
i= 1740
i= 1741
i= 1742
i= 1743
i= 1744
i= 1745
i= 1746
i= 1747
i= 1748
i= 1749
i= 1750
i= 1751
i= 1752
i= 1753
i= 1754
i= 1755
i= 1756
i= 1757
i= 1758
i= 1759
i= 1760
i= 1761
i= 1762
i= 1763
i= 1764
i= 1765
i= 1766
i= 1767
i= 1768
i= 1769
i= 1770
i= 1771
i= 1772
i= 1773
i= 1774
i= 1775
i= 1776
i= 1777
i= 1778
i= 1779
i= 1780
i= 1781
i= 1782
i= 1783
i= 1784
i= 1785
i= 1786
i= 1787
i= 1788
i= 1789
i= 1790
i= 1791
i= 1792
i= 1793
i= 1794
i= 1795
i= 1796
i= 1797
i= 1798
i= 1799
i= 1800
i= 1801
i= 1802
i= 1803
i= 1804
i= 1805
i= 1806
i= 1807
i= 1808
i= 1809
i= 1810
i= 1811
i= 1812
i= 1813
i= 1814
i= 1815
i= 1816
i= 1817
i= 1818
i= 1819
i= 1820
i= 1821
i= 1822
i= 1823
i= 1824
i= 1825
i= 1826
i= 1827
i= 1828
i= 1829
i= 1830
i= 1831
i= 1832
i= 1833
i= 1834
i= 1835
i= 1836
i= 1837
i= 1838
i= 1839
i= 1840
i= 1841
i= 1842
i= 1843
i= 1844
i= 1845
i= 1846
i= 1847
i= 1848
i= 1849
i= 1850
i= 1851
i= 1852
i= 1853
i= 1854
i= 1855
i= 1856
i= 1857
i= 1858
i= 1859
i= 1860
i= 1861
i= 1862
i= 1863
i= 1864
i= 1865
i= 1866
i= 1867
i= 1868
i= 1869
i= 1870
i= 1871
i= 1872
i= 1873
i= 1874
i= 1875
i= 1876
i= 1877
i= 1878
i= 1879
i= 1880
i= 1881
i= 1882
i= 1883
i= 1884
i= 1885
i= 1886
i= 1887
i= 1888
i= 1889
i= 1890
i= 1891
i= 1892
i= 1893
i= 1894
i= 1895
i= 1896
i= 1897
i= 1898
i= 1899
i= 1900
i= 1901
i= 1902
i= 1903
i= 1904
i= 1905
i= 1906
i= 1907
i= 1908
i= 1909
i= 1910
i= 1911
i= 1912
i= 1913
i= 1914
i= 1915
i= 1916
i= 1917
i= 1918
i= 1919
i= 1920
i= 1921
i= 1922
i= 1923
i= 1924
i= 1925
i= 1926
i= 1927
i= 1928
i= 1929
i= 1930
i= 1931
i= 1932
i= 1933
i= 1934
i= 1935
i= 1936
i= 1937
i= 1938
i= 1939
i= 1940
i= 1941
i= 1942
i= 1943
i= 1944
i= 1945
i= 1946
i= 1947
i= 1948
i= 1949
i= 1950
i= 1951
i= 1952
i= 1953
i= 1954
i= 1955
i= 1956
i= 1957
i= 1958
i= 1959
i= 1960
i= 1961
i= 1962
i= 1963
i= 1964
i= 1965
i= 1966
i= 1967
i= 1968
i= 1969
i= 1970
i= 1971
i= 1972
i= 1973
i= 1974
i= 1975
i= 1976
i= 1977
i= 1978
i= 1979
i= 1980
i= 1981
i= 1982
i= 1983
i= 1984
i= 1985
i= 1986
i= 1987
i= 1988
i= 1989
i= 1990
i= 1991
i= 1992
i= 1993
i= 1994
i= 1995
i= 1996
i= 1997
i= 1998
i= 1999
i= 2000
i= 2001
i= 2002
i= 2003
i= 2004
i= 2005
i= 2006
i= 2007
i= 2008
i= 2009
i= 2010
i= 2011
i= 2012
i= 2013
i= 2014
i= 2015
i= 2016
i= 2017
i= 2018
i= 2019
i= 2020
i= 2021
i= 2022
i= 2023
i= 2024
i= 2025
i= 2026
i= 2027
i= 2028
i= 2029
i= 2030
i= 2031
i= 2032
i= 2033
i= 2034
i= 2035
i= 2036
i= 2037
i= 2038
i= 2039
i= 2040
i= 2041
i= 2042
i= 2043
i= 2044
i= 2045
i= 2046
i= 2047
i= 2048
i= 2049
i= 2050
i= 2051
i= 2052
i= 2053
i= 2054
i= 2055
i= 2056
i= 2057
i= 2058
i= 2059
i= 2060
i= 2061
i= 2062
i= 2063
i= 2064
i= 2065
i= 2066
i= 2067
i= 2068
i= 2069
i= 2070
i= 2071
i= 2072
i= 2073
i= 2074
i= 2075
i= 2076
i= 2077
i= 2078
i= 2079
i= 2080
i= 2081
i= 2082
i= 2083
i= 2084
i= 2085
i= 2086
i= 2087
i= 2088
i= 2089
i= 2090
i= 2091
i= 2092
i= 2093
i= 2094
i= 2095
i= 2096
i= 2097
i= 2098
i= 2099
i= 2100
i= 2101
i= 2102
i= 2103
i= 2104
i= 2105
i= 2106
i= 2107
i= 2108
i= 2109
i= 2110
i= 2111
i= 2112
i= 2113
i= 2114
i= 2115
i= 2116
i= 2117
i= 2118
i= 2119
i= 2120
i= 2121
i= 2122
i= 2123
i= 2124
i= 2125
i= 2126
i= 2127
i= 2128
i= 2129
i= 2130
i= 2131
i= 2132
i= 2133
i= 2134
i= 2135
i= 2136
i= 2137
i= 2138
i= 2139
i= 2140
i= 2141
i= 2142
i= 2143
i= 2144
i= 2145
i= 2146
i= 2147
i= 2148
i= 2149
i= 2150
i= 2151
i= 2152
i= 2153
i= 2154
i= 2155
i= 2156
i= 2157
i= 2158
i= 2159
i= 2160
i= 2161
i= 2162
i= 2163
i= 2164
i= 2165
i= 2166
i= 2167
i= 2168
i= 2169
i= 2170
i= 2171
i= 2172
i= 2173
i= 2174
i= 2175
i= 2176
i= 2177
i= 2178
i= 2179
i= 2180
i= 2181
i= 2182
i= 2183
i= 2184
i= 2185
i= 2186
i= 2187
i= 2188
i= 2189
i= 2190
i= 2191
i= 2192

i= 2193
i= 2194
i= 2195
i= 2196
i= 2197
i= 2198
i= 2199
i= 2200
i= 2201
i= 2202
i= 2203
i= 2204
i= 2205
i= 2206
i= 2207
i= 2208
i= 2209
i= 2210
i= 2211
i= 2212
i= 2213
i= 2214
i= 2215
i= 2216
i= 2217
i= 2218
i= 2219
i= 2220
i= 2221
i= 2222
i= 2223
i= 2224
i= 2225
i= 2226
i= 2227
i= 2228
i= 2229
i= 2230
i= 2231
i= 2232
i= 2233
i= 2234
i= 2235
i= 2236
i= 2237
i= 2238
i= 2239
i= 2240
i= 2241
i= 2242
i= 2243
i= 2244
i= 2245
i= 2246
i= 2247
i= 2248
i= 2249
i= 2250
i= 2251
i= 2252
i= 2253
i= 2254
i= 2255
i= 2256
i= 2257
i= 2258
i= 2259
i= 2260
i= 2261
i= 2262
i= 2263
i= 2264
i= 2265
i= 2266
i= 2267
i= 2268
i= 2269
i= 2270
i= 2271
i= 2272
i= 2273
i= 2274
i= 2275
i= 2276
i= 2277
i= 2278
i= 2279
i= 2280
i= 2281
i= 2282
i= 2283
i= 2284
i= 2285
i= 2286
i= 2287
i= 2288
i= 2289
i= 2290
i= 2291
i= 2292
i= 2293
i= 2294
i= 2295
i= 2296
i= 2297
i= 2298
i= 2299
i= 2300
i= 2301
i= 2302
i= 2303
i= 2304
i= 2305
i= 2306
i= 2307
i= 2308
i= 2309
i= 2310
i= 2311
i= 2312
i= 2313
i= 2314
i= 2315
i= 2316
i= 2317
i= 2318
i= 2319
i= 2320
i= 2321
i= 2322
i= 2323
i= 2324
i= 2325
i= 2326
i= 2327
i= 2328
i= 2329
i= 2330
i= 2331
i= 2332
i= 2333
i= 2334
i= 2335
i= 2336
i= 2337
i= 2338
i= 2339
i= 2340
i= 2341
i= 2342
i= 2343
i= 2344
i= 2345
i= 2346
i= 2347
i= 2348
i= 2349
i= 2350
i= 2351
i= 2352
i= 2353
i= 2354
i= 2355
i= 2356
i= 2357
i= 2358
i= 2359
i= 2360
i= 2361
i= 2362
i= 2363
i= 2364
i= 2365
i= 2366
i= 2367
i= 2368
i= 2369
i= 2370
i= 2371
i= 2372
i= 2373
i= 2374
i= 2375
i= 2376
i= 2377
i= 2378
i= 2379
i= 2380
i= 2381
i= 2382
i= 2383
i= 2384
i= 2385
i= 2386
i= 2387
i= 2388
i= 2389
i= 2390
i= 2391
i= 2392
i= 2393
i= 2394
i= 2395
i= 2396
i= 2397
i= 2398
i= 2399
i= 2400
i= 2401
i= 2402
i= 2403
i= 2404
i= 2405
i= 2406
i= 2407
i= 2408
i= 2409
i= 2410
i= 2411
i= 2412
i= 2413
i= 2414
i= 2415
i= 2416
i= 2417
i= 2418
i= 2419
i= 2420
i= 2421
i= 2422
i= 2423
i= 2424
i= 2425
i= 2426
i= 2427
i= 2428
i= 2429
i= 2430
i= 2431
i= 2432
i= 2433
i= 2434
i= 2435
i= 2436
i= 2437
i= 2438
i= 2439
i= 2440
i= 2441
i= 2442
i= 2443
i= 2444
i= 2445
i= 2446
i= 2447
i= 2448
i= 2449
i= 2450
i= 2451
i= 2452
i= 2453
i= 2454
i= 2455
i= 2456
i= 2457
i= 2458
i= 2459
i= 2460
i= 2461
i= 2462
i= 2463
i= 2464
i= 2465
i= 2466
i= 2467
i= 2468
i= 2469
i= 2470
i= 2471
i= 2472
i= 2473
i= 2474
i= 2475
i= 2476
i= 2477
i= 2478
i= 2479
i= 2480
i= 2481
i= 2482
i= 2483
i= 2484
i= 2485
i= 2486
i= 2487
i= 2488
i= 2489
i= 2490
i= 2491
i= 2492
i= 2493
i= 2494
i= 2495
i= 2496
i= 2497
i= 2498
i= 2499
i= 2500
i= 2501
i= 2502
i= 2503
i= 2504
i= 2505
i= 2506
i= 2507
i= 2508
i= 2509
i= 2510
i= 2511
i= 2512
i= 2513
i= 2514
i= 2515
i= 2516
i= 2517
i= 2518
i= 2519
i= 2520
i= 2521
i= 2522
i= 2523
i= 2524
i= 2525
i= 2526
i= 2527
i= 2528
i= 2529
i= 2530
i= 2531
i= 2532
i= 2533
i= 2534
i= 2535
i= 2536
i= 2537
i= 2538
i= 2539
i= 2540
i= 2541
i= 2542
i= 2543
i= 2544
i= 2545
i= 2546
i= 2547
i= 2548
i= 2549
i= 2550
i= 2551
i= 2552
i= 2553
i= 2554
i= 2555
i= 2556
i= 2557
i= 2558
i= 2559
i= 2560
i= 2561
i= 2562
i= 2563
i= 2564
i= 2565
i= 2566
i= 2567
i= 2568
i= 2569
i= 2570
i= 2571
i= 2572
i= 2573
i= 2574
i= 2575
i= 2576
i= 2577
i= 2578
i= 2579
i= 2580
i= 2581
i= 2582
i= 2583
i= 2584
i= 2585
i= 2586
i= 2587
i= 2588
i= 2589
i= 2590
i= 2591
i= 2592
i= 2593
i= 2594
i= 2595
i= 2596
i= 2597
i= 2598
i= 2599
i= 2600
i= 2601
i= 2602
i= 2603
i= 2604
i= 2605
i= 2606
i= 2607
i= 2608
i= 2609
i= 2610
i= 2611
i= 2612
i= 2613
i= 2614
i= 2615
i= 2616
i= 2617
i= 2618
i= 2619
i= 2620
i= 2621
i= 2622
i= 2623
i= 2624
i= 2625
i= 2626
i= 2627
i= 2628
i= 2629
i= 2630
i= 2631
i= 2632
i= 2633
i= 2634
i= 2635
i= 2636
i= 2637
i= 2638
i= 2639
i= 2640
i= 2641
i= 2642
i= 2643
i= 2644
i= 2645
i= 2646
i= 2647
i= 2648
i= 2649
i= 2650
i= 2651
i= 2652
i= 2653
i= 2654
i= 2655
i= 2656
i= 2657
i= 2658
i= 2659
i= 2660
i= 2661
i= 2662
i= 2663
i= 2664
i= 2665
i= 2666
i= 2667
i= 2668
i= 2669
i= 2670
i= 2671
i= 2672
i= 2673
i= 2674
i= 2675
i= 2676
i= 2677
i= 2678
i= 2679
i= 2680
i= 2681
i= 2682
i= 2683
i= 2684
i= 2685
i= 2686
i= 2687
i= 2688
i= 2689
i= 2690
i= 2691
i= 2692
i= 2693
i= 2694
i= 2695
i= 2696
i= 2697
i= 2698
i= 2699
i= 2700
i= 2701
i= 2702
i= 2703
i= 2704
i= 2705
i= 2706
i= 2707
i= 2708
i= 2709
i= 2710
i= 2711
i= 2712
i= 2713
i= 2714
i= 2715
i= 2716
i= 2717
i= 2718
i= 2719
i= 2720
i= 2721
i= 2722
i= 2723
i= 2724
i= 2725
i= 2726
i= 2727
i= 2728
i= 2729
i= 2730
i= 2731
i= 2732
i= 2733
i= 2734
i= 2735
i= 2736
i= 2737
i= 2738
i= 2739
i= 2740
i= 2741
i= 2742
i= 2743
i= 2744
i= 2745
i= 2746
i= 2747
i= 2748
i= 2749
i= 2750
i= 2751
i= 2752
i= 2753
i= 2754
i= 2755
i= 2756
i= 2757
i= 2758
i= 2759
i= 2760
i= 2761
i= 2762
i= 2763
i= 2764
i= 2765
i= 2766
i= 2767
i= 2768
i= 2769
i= 2770
i= 2771
i= 2772
i= 2773
i= 2774
i= 2775
i= 2776
i= 2777
i= 2778
i= 2779
i= 2780
i= 2781
i= 2782
i= 2783
i= 2784
i= 2785
i= 2786
i= 2787
i= 2788
i= 2789
i= 2790
i= 2791
i= 2792
i= 2793
i= 2794
i= 2795
i= 2796
i= 2797
i= 2798
i= 2799
i= 2800
i= 2801
i= 2802
i= 2803
i= 2804
i= 2805
i= 2806
i= 2807
i= 2808
i= 2809
i= 2810
i= 2811
i= 2812
i= 2813
i= 2814
i= 2815
i= 2816
i= 2817
i= 2818
i= 2819
i= 2820
i= 2821
i= 2822
i= 2823
i= 2824
i= 2825
i= 2826
i= 2827
i= 2828
i= 2829
i= 2830
i= 2831
i= 2832
i= 2833
i= 2834
i= 2835
i= 2836
i= 2837
i= 2838
i= 2839
i= 2840
i= 2841
i= 2842
i= 2843
i= 2844
i= 2845
i= 2846
i= 2847
i= 2848
i= 2849
i= 2850
i= 2851
i= 2852
i= 2853
i= 2854
i= 2855
i= 2856
i= 2857
i= 2858
i= 2859
i= 2860
i= 2861
i= 2862
i= 2863
i= 2864
i= 2865
i= 2866
i= 2867
i= 2868
i= 2869
i= 2870
i= 2871
i= 2872
i= 2873
i= 2874
i= 2875
i= 2876
i= 2877
i= 2878
i= 2879
i= 2880
i= 2881
i= 2882
i= 2883
i= 2884
i= 2885
i= 2886
i= 2887
i= 2888
i= 2889
i= 2890
i= 2891
i= 2892
i= 2893
i= 2894
i= 2895
i= 2896
i= 2897
i= 2898
i= 2899
i= 2900
i= 2901
i= 2902
i= 2903
i= 2904
i= 2905
i= 2906
i= 2907
i= 2908
i= 2909
i= 2910
i= 2911
i= 2912
i= 2913
i= 2914
i= 2915
i= 2916
i= 2917
i= 2918
i= 2919
i= 2920
i= 2921
i= 2922
i= 2923
i= 2924
i= 2925
i= 2926
i= 2927
i= 2928
i= 2929
i= 2930
i= 2931
i= 2932
i= 2933
i= 2934
i= 2935
i= 2936
i= 2937
i= 2938
i= 2939
i= 2940
i= 2941
i= 2942
i= 2943
i= 2944
i= 2945
i= 2946
i= 2947
i= 2948
i= 2949
i= 2950
i= 2951
i= 2952
i= 2953
i= 2954
i= 2955
i= 2956
i= 2957
i= 2958
i= 2959
i= 2960
i= 2961
i= 2962
i= 2963
i= 2964
i= 2965
i= 2966
i= 2967
i= 2968
i= 2969
i= 2970
i= 2971
i= 2972
i= 2973
i= 2974
i= 2975
i= 2976
i= 2977
i= 2978
i= 2979
i= 2980
i= 2981
i= 2982
i= 2983
i= 2984
i= 2985
i= 2986
i= 2987
i= 2988
i= 2989
i= 2990
i= 2991
i= 2992
i= 2993
i= 2994
i= 2995
i= 2996
i= 2997
i= 2998
i= 2999
i= 3000
i= 3001
i= 3002
i= 3003
i= 3004
i= 3005
i= 3006
i= 3007
i= 3008
i= 3009
i= 3010
i= 3011
i= 3012
i= 3013
i= 3014
i= 3015
i= 3016
i= 3017
i= 3018
i= 3019
i= 3020
i= 3021
i= 3022
i= 3023
i= 3024
i= 3025
i= 3026
i= 3027
i= 3028
i= 3029
i= 3030
i= 3031
i= 3032
i= 3033
i= 3034
i= 3035
i= 3036
i= 3037
i= 3038
i= 3039
i= 3040
i= 3041
i= 3042
i= 3043
i= 3044
i= 3045
i= 3046
i= 3047
i= 3048
i= 3049
i= 3050
i= 3051
i= 3052
i= 3053
i= 3054
i= 3055
i= 3056
i= 3057
i= 3058
i= 3059
i= 3060
i= 3061
i= 3062
i= 3063
i= 3064
i= 3065
i= 3066
i= 3067
i= 3068
i= 3069
i= 3070
i= 3071
i= 3072
i= 3073
i= 3074
i= 3075
i= 3076
i= 3077
i= 3078
i= 3079
i= 3080
i= 3081
i= 3082
i= 3083
i= 3084
i= 3085
i= 3086
i= 3087
i= 3088
i= 3089
i= 3090
i= 3091
i= 3092
i= 3093
i= 3094
i= 3095
i= 3096
i= 3097
i= 3098
i= 3099
i= 3100
i= 3101
i= 3102
i= 3103
i= 3104
i= 3105
i= 3106
i= 3107
i= 3108
i= 3109
i= 3110
i= 3111
i= 3112
i= 3113
i= 3114
i= 3115
i= 3116
i= 3117
i= 3118
i= 3119
i= 3120
i= 3121
i= 3122
i= 3123
i= 3124
i= 3125
i= 3126
i= 3127
i= 3128
i= 3129
i= 3130
i= 3131
i= 3132
i= 3133
i= 3134
i= 3135
i= 3136
i= 3137
i= 3138
i= 3139
i= 3140
i= 3141
i= 3142
i= 3143
i= 3144
i= 3145
i= 3146
i= 3147
i= 3148
i= 3149
i= 3150
i= 3151
i= 3152
i= 3153
i= 3154
i= 3155
i= 3156
i= 3157
i= 3158
i= 3159
i= 3160
i= 3161
i= 3162
i= 3163
i= 3164
i= 3165
i= 3166
i= 3167
i= 3168
i= 3169
i= 3170
i= 3171
i= 3172
i= 3173
i= 3174
i= 3175
i= 3176
i= 3177
i= 3178
i= 3179
i= 3180
i= 3181
i= 3182
i= 3183
i= 3184
i= 3185
i= 3186
i= 3187
i= 3188
i= 3189
i= 3190
i= 3191
i= 3192
i= 3193
i= 3194
i= 3195
i= 3196
i= 3197
i= 3198
i= 3199
i= 3200
i= 3201
i= 3202
i= 3203
i= 3204
i= 3205
i= 3206
i= 3207
i= 3208
i= 3209
i= 3210
i= 3211
i= 3212
i= 3213
i= 3214
i= 3215
i= 3216
i= 3217
i= 3218

i= 3219
i= 3220
i= 3221
i= 3222
i= 3223
i= 3224
i= 3225
i= 3226
i= 3227
i= 3228
i= 3229
i= 3230
i= 3231
i= 3232
i= 3233
i= 3234
i= 3235
i= 3236
i= 3237
i= 3238
i= 3239
i= 3240
i= 3241
i= 3242
i= 3243
i= 3244
i= 3245
i= 3246
i= 3247
i= 3248
i= 3249
i= 3250
i= 3251
i= 3252
i= 3253
i= 3254
i= 3255
i= 3256
i= 3257
i= 3258
i= 3259
i= 3260
i= 3261
i= 3262
i= 3263
i= 3264
i= 3265
i= 3266
i= 3267
i= 3268
i= 3269
i= 3270
i= 3271
i= 3272
i= 3273
i= 3274
i= 3275
i= 3276
i= 3277
i= 3278
i= 3279
i= 3280
i= 3281
i= 3282
i= 3283
i= 3284
i= 3285
i= 3286
i= 3287
i= 3288
i= 3289
i= 3290
i= 3291
i= 3292
i= 3293
i= 3294
i= 3295
i= 3296
i= 3297
i= 3298
i= 3299
i= 3300
i= 3301
i= 3302
i= 3303
i= 3304
i= 3305
i= 3306
i= 3307
i= 3308
i= 3309
i= 3310
i= 3311
i= 3312
i= 3313
i= 3314
i= 3315
i= 3316
i= 3317
i= 3318
i= 3319
i= 3320
i= 3321
i= 3322
i= 3323
i= 3324
i= 3325
i= 3326
i= 3327
i= 3328
i= 3329
i= 3330
i= 3331
i= 3332
i= 3333
i= 3334
i= 3335
i= 3336
i= 3337
i= 3338
i= 3339
i= 3340
i= 3341
i= 3342
i= 3343
i= 3344
i= 3345
i= 3346
i= 3347
i= 3348
i= 3349
i= 3350
i= 3351
i= 3352
i= 3353
i= 3354
i= 3355
i= 3356
i= 3357
i= 3358
i= 3359
i= 3360
i= 3361
i= 3362
i= 3363
i= 3364
i= 3365
i= 3366
i= 3367
i= 3368
i= 3369
i= 3370
i= 3371
i= 3372
i= 3373
i= 3374
i= 3375
i= 3376
i= 3377
i= 3378
i= 3379
i= 3380
i= 3381
i= 3382
i= 3383
i= 3384
i= 3385
i= 3386
i= 3387
i= 3388
i= 3389
i= 3390
i= 3391
i= 3392
i= 3393
i= 3394
i= 3395
i= 3396
i= 3397
i= 3398
i= 3399
i= 3400
i= 3401
i= 3402
i= 3403
i= 3404
i= 3405
i= 3406
i= 3407
i= 3408
i= 3409
i= 3410
i= 3411
i= 3412
i= 3413
i= 3414
i= 3415
i= 3416
i= 3417
i= 3418
i= 3419
i= 3420
i= 3421
i= 3422
i= 3423
i= 3424
i= 3425
i= 3426
i= 3427
i= 3428
i= 3429
i= 3430
i= 3431
i= 3432
i= 3433
i= 3434
i= 3435
i= 3436
i= 3437
i= 3438
i= 3439
i= 3440
i= 3441
i= 3442
i= 3443
i= 3444
i= 3445
i= 3446
i= 3447
i= 3448
i= 3449
i= 3450
i= 3451
i= 3452
i= 3453
i= 3454
i= 3455
i= 3456
i= 3457
i= 3458
i= 3459
i= 3460
i= 3461
i= 3462
i= 3463
i= 3464
i= 3465
i= 3466
i= 3467
i= 3468
i= 3469
i= 3470
i= 3471
i= 3472
i= 3473
i= 3474
i= 3475
i= 3476
i= 3477
i= 3478
i= 3479
i= 3480
i= 3481
i= 3482
i= 3483
i= 3484
i= 3485
i= 3486
i= 3487
i= 3488
i= 3489
i= 3490
i= 3491
i= 3492
i= 3493
i= 3494
i= 3495
i= 3496
i= 3497
i= 3498
i= 3499
i= 3500
i= 3501
i= 3502
i= 3503
i= 3504
i= 3505
i= 3506
i= 3507
i= 3508
i= 3509
i= 3510
i= 3511
i= 3512
i= 3513
i= 3514
i= 3515
i= 3516
i= 3517
i= 3518
i= 3519
i= 3520
i= 3521
i= 3522
i= 3523
i= 3524
i= 3525
i= 3526
i= 3527
i= 3528
i= 3529
i= 3530
i= 3531
i= 3532
i= 3533
i= 3534
i= 3535
i= 3536
i= 3537
i= 3538
i= 3539
i= 3540
i= 3541
i= 3542
i= 3543
i= 3544
i= 3545
i= 3546
i= 3547
i= 3548
i= 3549
i= 3550
i= 3551
i= 3552
i= 3553
i= 3554
i= 3555
i= 3556
i= 3557
i= 3558
i= 3559
i= 3560
i= 3561
i= 3562
i= 3563
i= 3564
i= 3565
i= 3566
i= 3567
i= 3568
i= 3569
i= 3570
i= 3571
i= 3572
i= 3573
i= 3574
i= 3575
i= 3576
i= 3577
i= 3578
i= 3579
i= 3580
i= 3581
i= 3582
i= 3583
i= 3584
i= 3585
i= 3586
i= 3587
i= 3588
i= 3589
i= 3590
i= 3591
i= 3592
i= 3593
i= 3594
i= 3595
i= 3596
i= 3597
i= 3598
i= 3599
i= 3600
i= 3601
i= 3602
i= 3603
i= 3604
i= 3605
i= 3606
i= 3607
i= 3608
i= 3609
i= 3610
i= 3611
i= 3612
i= 3613
i= 3614
i= 3615
i= 3616
i= 3617
i= 3618
i= 3619
i= 3620
i= 3621
i= 3622
i= 3623
i= 3624
i= 3625
i= 3626
i= 3627
i= 3628
i= 3629
i= 3630
i= 3631
i= 3632
i= 3633
i= 3634
i= 3635
i= 3636
i= 3637
i= 3638
i= 3639
i= 3640
i= 3641
i= 3642
i= 3643
i= 3644
i= 3645
i= 3646
i= 3647
i= 3648
i= 3649
i= 3650
i= 3651
i= 3652
i= 3653
i= 3654
i= 3655
i= 3656
i= 3657
i= 3658
i= 3659
i= 3660
i= 3661
i= 3662
i= 3663
i= 3664
i= 3665
i= 3666
i= 3667
i= 3668
i= 3669
i= 3670
i= 3671
i= 3672
i= 3673
i= 3674
i= 3675
i= 3676
i= 3677
i= 3678
i= 3679
i= 3680
i= 3681
i= 3682
i= 3683
i= 3684
i= 3685
i= 3686
i= 3687
i= 3688
i= 3689
i= 3690
i= 3691
i= 3692
i= 3693
i= 3694
i= 3695
i= 3696
i= 3697
i= 3698
i= 3699
i= 3700
i= 3701
i= 3702
i= 3703
i= 3704
i= 3705
i= 3706
i= 3707
i= 3708
i= 3709
i= 3710
i= 3711
i= 3712
i= 3713
i= 3714
i= 3715
i= 3716
i= 3717
i= 3718
i= 3719
i= 3720
i= 3721
i= 3722
i= 3723
i= 3724
i= 3725
i= 3726
i= 3727
i= 3728
i= 3729
i= 3730
i= 3731
i= 3732
i= 3733
i= 3734
i= 3735
i= 3736
i= 3737
i= 3738
i= 3739
i= 3740
i= 3741
i= 3742
i= 3743
i= 3744
i= 3745
i= 3746
i= 3747
i= 3748
i= 3749
i= 3750
i= 3751
i= 3752
i= 3753
i= 3754
i= 3755
i= 3756
i= 3757
i= 3758
i= 3759
i= 3760
i= 3761
i= 3762
i= 3763
i= 3764
i= 3765
i= 3766
i= 3767
i= 3768
i= 3769
i= 3770
i= 3771
i= 3772
i= 3773
i= 3774
i= 3775
i= 3776
i= 3777
i= 3778
i= 3779
i= 3780
i= 3781
i= 3782
i= 3783
i= 3784
i= 3785
i= 3786
i= 3787
i= 3788
i= 3789
i= 3790
i= 3791
i= 3792
i= 3793
i= 3794
i= 3795
i= 3796
i= 3797
i= 3798
i= 3799
i= 3800
i= 3801
i= 3802
i= 3803
i= 3804
i= 3805
i= 3806
i= 3807
i= 3808
i= 3809
i= 3810
i= 3811
i= 3812
i= 3813
i= 3814
i= 3815
i= 3816
i= 3817
i= 3818
i= 3819
i= 3820
i= 3821
i= 3822
i= 3823
i= 3824
i= 3825
i= 3826
i= 3827
i= 3828
i= 3829
i= 3830
i= 3831
i= 3832
i= 3833
i= 3834
i= 3835
i= 3836
i= 3837
i= 3838
i= 3839
i= 3840
i= 3841
i= 3842
i= 3843
i= 3844
i= 3845
i= 3846
i= 3847
i= 3848
i= 3849
i= 3850
i= 3851
i= 3852
i= 3853
i= 3854
i= 3855
i= 3856
i= 3857
i= 3858
i= 3859
i= 3860
i= 3861
i= 3862
i= 3863
i= 3864
i= 3865
i= 3866
i= 3867
i= 3868
i= 3869
i= 3870
i= 3871
i= 3872
i= 3873
i= 3874
i= 3875
i= 3876
i= 3877
i= 3878
i= 3879
i= 3880
i= 3881
i= 3882
i= 3883
i= 3884
i= 3885
i= 3886
i= 3887
i= 3888
i= 3889
i= 3890
i= 3891
i= 3892
i= 3893
i= 3894
i= 3895
i= 3896
i= 3897
i= 3898
i= 3899
i= 3900
i= 3901
i= 3902
i= 3903
i= 3904
i= 3905
i= 3906
i= 3907
i= 3908
i= 3909
i= 3910
i= 3911
i= 3912
i= 3913
i= 3914
i= 3915
i= 3916
i= 3917
i= 3918
i= 3919
i= 3920
i= 3921
i= 3922
i= 3923
i= 3924
i= 3925
i= 3926
i= 3927
i= 3928
i= 3929
i= 3930
i= 3931
i= 3932
i= 3933
i= 3934
i= 3935
i= 3936
i= 3937
i= 3938
i= 3939
i= 3940
i= 3941
i= 3942
i= 3943
i= 3944
i= 3945
i= 3946
i= 3947
i= 3948
i= 3949
i= 3950
i= 3951
i= 3952
i= 3953
i= 3954
i= 3955
i= 3956
i= 3957
i= 3958
i= 3959
i= 3960
i= 3961
i= 3962
i= 3963
i= 3964
i= 3965
i= 3966
i= 3967
i= 3968
i= 3969
i= 3970
i= 3971
i= 3972
i= 3973
i= 3974
i= 3975
i= 3976
i= 3977
i= 3978
i= 3979
i= 3980
i= 3981
i= 3982
i= 3983
i= 3984
i= 3985
i= 3986
i= 3987
i= 3988
i= 3989
i= 3990
i= 3991
i= 3992
i= 3993
i= 3994
i= 3995
i= 3996
i= 3997
i= 3998
i= 3999
i= 4000
i= 4001
i= 4002
i= 4003
i= 4004
i= 4005
i= 4006
i= 4007
i= 4008
i= 4009
i= 4010
i= 4011
i= 4012
i= 4013
i= 4014
i= 4015
i= 4016
i= 4017
i= 4018
i= 4019
i= 4020
i= 4021
i= 4022
i= 4023
i= 4024
i= 4025
i= 4026
i= 4027
i= 4028
i= 4029
i= 4030
i= 4031
i= 4032
i= 4033
i= 4034
i= 4035
i= 4036
i= 4037
i= 4038
i= 4039
i= 4040
i= 4041
i= 4042
i= 4043
i= 4044
i= 4045
i= 4046
i= 4047
i= 4048
i= 4049
i= 4050
i= 4051
i= 4052
i= 4053
i= 4054
i= 4055
i= 4056
i= 4057
i= 4058
i= 4059
i= 4060
i= 4061
i= 4062
i= 4063
i= 4064
i= 4065
i= 4066
i= 4067
i= 4068
i= 4069
i= 4070
i= 4071
i= 4072
i= 4073
i= 4074
i= 4075
i= 4076
i= 4077
i= 4078
i= 4079
i= 4080
i= 4081
i= 4082
i= 4083
i= 4084
i= 4085
i= 4086
i= 4087
i= 4088
i= 4089
i= 4090
i= 4091
i= 4092
i= 4093
i= 4094
i= 4095
i= 4096
i= 4097
i= 4098
i= 4099
i= 4100
i= 4101
i= 4102
i= 4103
i= 4104
i= 4105
i= 4106
i= 4107
i= 4108
i= 4109
i= 4110
i= 4111
i= 4112
i= 4113
i= 4114
i= 4115
i= 4116
i= 4117
i= 4118
i= 4119
i= 4120
i= 4121
i= 4122
i= 4123
i= 4124
i= 4125
i= 4126
i= 4127
i= 4128
i= 4129
i= 4130
i= 4131
i= 4132
i= 4133
i= 4134
i= 4135
i= 4136
i= 4137
i= 4138
i= 4139
i= 4140
i= 4141
i= 4142
i= 4143
i= 4144
i= 4145
i= 4146
i= 4147
i= 4148
i= 4149
i= 4150
i= 4151
i= 4152
i= 4153
i= 4154
i= 4155
i= 4156
i= 4157
i= 4158
i= 4159
i= 4160
i= 4161
i= 4162
i= 4163
i= 4164
i= 4165
i= 4166
i= 4167
i= 4168
i= 4169
i= 4170
i= 4171
i= 4172
i= 4173
i= 4174
i= 4175
i= 4176
i= 4177
i= 4178
i= 4179
i= 4180
i= 4181
i= 4182
i= 4183
i= 4184
i= 4185
i= 4186
i= 4187
i= 4188
i= 4189
i= 4190
i= 4191
i= 4192
i= 4193
i= 4194
i= 4195
i= 4196
i= 4197
i= 4198
i= 4199
i= 4200
i= 4201
i= 4202
i= 4203
i= 4204
i= 4205
i= 4206
i= 4207
i= 4208
i= 4209
i= 4210
i= 4211
i= 4212
i= 4213
i= 4214
i= 4215
i= 4216
i= 4217
i= 4218
i= 4219
i= 4220
i= 4221
i= 4222
i= 4223
i= 4224
i= 4225
i= 4226
i= 4227
i= 4228
i= 4229
i= 4230
i= 4231
i= 4232
i= 4233
i= 4234
i= 4235
i= 4236
i= 4237
i= 4238
i= 4239
i= 4240
i= 4241
i= 4242
i= 4243
i= 4244

i= 4245
i= 4246
i= 4247
i= 4248
i= 4249
i= 4250
i= 4251
i= 4252
i= 4253
i= 4254
i= 4255
i= 4256
i= 4257
i= 4258
i= 4259
i= 4260
i= 4261
i= 4262
i= 4263
i= 4264
i= 4265
i= 4266
i= 4267
i= 4268
i= 4269
i= 4270
i= 4271
i= 4272
i= 4273
i= 4274
i= 4275
i= 4276
i= 4277
i= 4278
i= 4279
i= 4280
i= 4281
i= 4282
i= 4283
i= 4284
i= 4285
i= 4286
i= 4287
i= 4288
i= 4289
i= 4290
i= 4291
i= 4292
i= 4293
i= 4294
i= 4295
i= 4296
i= 4297
i= 4298
i= 4299
i= 4300
i= 4301
i= 4302
i= 4303
i= 4304
i= 4305
i= 4306
i= 4307
i= 4308
i= 4309
i= 4310
i= 4311
i= 4312
i= 4313
i= 4314
i= 4315
i= 4316
i= 4317
i= 4318
i= 4319
i= 4320
i= 4321
i= 4322
i= 4323
i= 4324
i= 4325
i= 4326
i= 4327
i= 4328
i= 4329
i= 4330
i= 4331
i= 4332
i= 4333
i= 4334
i= 4335
i= 4336
i= 4337
i= 4338
i= 4339
i= 4340
i= 4341
i= 4342
i= 4343
i= 4344
i= 4345
i= 4346
i= 4347
i= 4348
i= 4349
i= 4350
i= 4351
i= 4352
i= 4353
i= 4354
i= 4355
i= 4356
i= 4357
i= 4358
i= 4359
i= 4360
i= 4361
i= 4362
i= 4363
i= 4364
i= 4365
i= 4366
i= 4367
i= 4368
i= 4369
i= 4370
i= 4371
i= 4372
i= 4373
i= 4374
i= 4375
i= 4376
i= 4377
i= 4378
i= 4379
i= 4380
i= 4381
i= 4382
i= 4383
i= 4384
i= 4385
i= 4386
i= 4387
i= 4388
i= 4389
i= 4390
i= 4391
i= 4392
i= 4393
i= 4394
i= 4395
i= 4396
i= 4397
i= 4398
i= 4399
i= 4400
i= 4401
i= 4402
i= 4403
i= 4404
i= 4405
i= 4406
i= 4407
i= 4408
i= 4409
i= 4410
i= 4411
i= 4412
i= 4413
i= 4414
i= 4415
i= 4416
i= 4417
i= 4418
i= 4419
i= 4420
i= 4421
i= 4422
i= 4423
i= 4424
i= 4425
i= 4426
i= 4427
i= 4428
i= 4429
i= 4430
i= 4431
i= 4432
i= 4433
i= 4434
i= 4435
i= 4436
i= 4437
i= 4438
i= 4439
i= 4440
i= 4441
i= 4442
i= 4443
i= 4444
i= 4445
i= 4446
i= 4447
i= 4448
i= 4449
i= 4450
i= 4451
i= 4452
i= 4453
i= 4454
i= 4455
i= 4456
i= 4457
i= 4458
i= 4459
i= 4460
i= 4461
i= 4462
i= 4463
i= 4464
i= 4465
i= 4466
i= 4467
i= 4468
i= 4469
i= 4470
i= 4471
i= 4472
i= 4473
i= 4474
i= 4475
i= 4476
i= 4477
i= 4478
i= 4479
i= 4480
i= 4481
i= 4482
i= 4483
i= 4484
i= 4485
i= 4486
i= 4487
i= 4488
i= 4489
i= 4490
i= 4491
i= 4492
i= 4493
i= 4494
i= 4495
i= 4496
i= 4497
i= 4498
i= 4499
i= 4500
i= 4501
i= 4502
i= 4503
i= 4504
i= 4505
i= 4506
i= 4507
i= 4508
i= 4509
i= 4510
i= 4511
i= 4512
i= 4513
i= 4514
i= 4515
i= 4516
i= 4517
i= 4518
i= 4519
i= 4520
i= 4521
i= 4522
i= 4523
i= 4524
i= 4525
i= 4526
i= 4527
i= 4528
i= 4529
i= 4530
i= 4531
i= 4532
i= 4533
i= 4534
i= 4535
i= 4536
i= 4537
i= 4538
i= 4539
i= 4540
i= 4541
i= 4542
i= 4543
i= 4544
i= 4545
i= 4546
i= 4547
i= 4548
i= 4549
i= 4550
i= 4551
i= 4552
i= 4553
i= 4554
i= 4555
i= 4556
i= 4557
i= 4558
i= 4559
i= 4560
i= 4561
i= 4562
i= 4563
i= 4564
i= 4565
i= 4566
i= 4567
i= 4568
i= 4569
i= 4570
i= 4571
i= 4572
i= 4573
i= 4574
i= 4575
i= 4576
i= 4577
i= 4578
i= 4579
i= 4580
i= 4581
i= 4582
i= 4583
i= 4584
i= 4585
i= 4586
i= 4587
i= 4588
i= 4589
i= 4590
i= 4591
i= 4592
i= 4593
i= 4594
i= 4595
i= 4596
i= 4597
i= 4598
i= 4599
i= 4600
i= 4601
i= 4602
i= 4603
i= 4604
i= 4605
i= 4606
i= 4607
i= 4608
i= 4609
i= 4610
i= 4611
i= 4612
i= 4613
i= 4614
i= 4615
i= 4616
i= 4617
i= 4618
i= 4619
i= 4620
i= 4621
i= 4622
i= 4623
i= 4624
i= 4625
i= 4626
i= 4627
i= 4628
i= 4629
i= 4630
i= 4631
i= 4632
i= 4633
i= 4634
i= 4635
i= 4636
i= 4637
i= 4638
i= 4639
i= 4640
i= 4641
i= 4642
i= 4643
i= 4644
i= 4645
i= 4646
i= 4647
i= 4648
i= 4649
i= 4650
i= 4651
i= 4652
i= 4653
i= 4654
i= 4655
i= 4656
i= 4657
i= 4658
i= 4659
i= 4660
i= 4661
i= 4662
i= 4663
i= 4664
i= 4665
i= 4666
i= 4667
i= 4668
i= 4669
i= 4670
i= 4671
i= 4672
i= 4673
i= 4674
i= 4675
i= 4676
i= 4677
i= 4678
i= 4679
i= 4680
i= 4681
i= 4682
i= 4683
i= 4684
i= 4685
i= 4686
i= 4687
i= 4688
i= 4689
i= 4690
i= 4691
i= 4692
i= 4693
i= 4694
i= 4695
i= 4696
i= 4697
i= 4698
i= 4699
i= 4700
i= 4701
i= 4702
i= 4703
i= 4704
i= 4705
i= 4706
i= 4707
i= 4708
i= 4709
i= 4710
i= 4711
i= 4712
i= 4713
i= 4714
i= 4715
i= 4716
i= 4717
i= 4718
i= 4719
i= 4720
i= 4721
i= 4722
i= 4723
i= 4724
i= 4725
i= 4726
i= 4727
i= 4728
i= 4729
i= 4730
i= 4731
i= 4732
i= 4733
i= 4734
i= 4735
i= 4736
i= 4737
i= 4738
i= 4739
i= 4740
i= 4741
i= 4742
i= 4743
i= 4744
i= 4745
i= 4746
i= 4747
i= 4748
i= 4749
i= 4750
i= 4751
i= 4752
i= 4753
i= 4754
i= 4755
i= 4756
i= 4757
i= 4758
i= 4759
i= 4760
i= 4761
i= 4762
i= 4763
i= 4764
i= 4765
i= 4766
i= 4767
i= 4768
i= 4769
i= 4770
i= 4771
i= 4772
i= 4773
i= 4774
i= 4775
i= 4776
i= 4777
i= 4778
i= 4779
i= 4780
i= 4781
i= 4782
i= 4783
i= 4784
i= 4785
i= 4786
i= 4787
i= 4788
i= 4789
i= 4790
i= 4791
i= 4792
i= 4793
i= 4794
i= 4795
i= 4796
i= 4797
i= 4798
i= 4799
i= 4800
i= 4801
i= 4802

In [222]:
crewNode[['gender','id']] = crewNode[['gender','id']].astype(int)

In [ ]:
crewNode1 = crewNode.drop(['credit_id'],axis=1,inplace=True)

In [318]:
crewNode['category'] = 'Crew'

In [319]:
crewNode.to_csv('crewNode.csv',sep=',', header=True, index=False)

In [320]:
crewNode.head()

,department,gender,id,job,name,movie_id,category
0,Editing,0,1721,Editor,Stephen E. Rivkin,19995,Crew
1,Art,2,496,Production Design,Rick Carter,19995,Crew
2,Sound,0,900,Sound Designer,Christopher Boyes,19995,Crew
3,Sound,0,900,Supervising Sound Editor,Christopher Boyes,19995,Crew
4,Production,1,1262,Casting,Mali Finn,19995,Crew

In [ ]:
# Director Node

In [289]:
directorNode = crewNode[crewNode['job']=='Director']
# directorNode1 = directorNode.drop(['credit_id'],axis=1,inplace=True)

In [290]:
directorNode.head()

  department  gender    id       job               name  movie_id
6  Directing       2  2710  Director      James Cameron     19995
1  Directing       2  1704  Director     Gore Verbinski       285
1  Directing       2    39  Director         Sam Mendes    206647
3  Directing       2   525  Director  Christopher Nolan     49026
1  Directing       2     7  Director     Andrew Stanton     49529

In [291]:
directorNode = directorNode.reset_index()
directorNode2 = directorNode.drop(['index'],axis=1,inplace=True)

In [292]:
directorNode[['movie_id']] = directorNode[['movie_id']].astype(str)

In [315]:
directorNode['category'] = 'Director'

In [293]:
# 按name合并多行
def ab(df):
    return','.join(df.values)
    
directorNode = directorNode.groupby(['id','name','gender'])['movie_id'].apply(ab)
directorNode = directorNode.reset_index()

In [295]:
directorNode['movie_id'][0]

'1895,1894,1893,11,838'

In [316]:
directorNode.head()

,id,name,gender,movie_id,category
0,1,George Lucas,2,"1895,1894,1893,11,838",Director
1,7,Andrew Stanton,2,"49529,10681,12,9487",Director
2,8,Lee Unkrich,2,10193,Director
3,13,Albert Brooks,2,37718,Director
4,24,Robert Zemeckis,2,"17979,5255,2310,2655,686,8358,13,9374,165,196,...",Director

In [317]:
directorNode.to_csv('directorNode.csv',sep=',', header=True, index=False)

In [302]:
#Movie Node最后的简化
movies.head(1)

,category,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,...,production,visual_effects,costume,camera,lighting,writing,crew_member,genres_bin,cast_bin,director_bin
0,movie,237000000,"[Action, Adventure, Fantasy, Science Fiction]",http://www.avatarmovie.com/,19995,"[culture clash, future, space war, space colon...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,...,"[1262, 2710, 6347, 8529, 20294, 1016177, 14017...","[6690, 113145, 93214, 957874, 1204668, 1206410...","[8527, 17675, 29067, 1071680, 1202850, 1310064...","[18265, 33302, 72201, 1177364, 1398970, 1401806]","[1401805, 1401807, 1453938]",[2710],"[42288, 58188, 89714, 122607, 236696, 956198, ...","[1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, ...","[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."

In [303]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 36 columns):
category                4803 non-null object
budget                  4803 non-null int64
genres                  4803 non-null object
homepage                1712 non-null object
id                      4803 non-null int64
keywords                4803 non-null object
original_language       4803 non-null object
original_title          4803 non-null object
overview                4800 non-null object
popularity              4803 non-null float64
production_companies    4803 non-null object
production_countries    4803 non-null object
release_date            4802 non-null object
revenue                 4803 non-null int64
runtime                 4801 non-null float64
spoken_languages        4803 non-null object
status                  4803 non-null object
tagline                 3959 non-null object
title                   4803 non-null object
vote_average            4803 non-null float64
vote_count              4803 non-null int64
main_cast               4803 non-null object
director                4803 non-null object
editing                 4803 non-null object
sound                   4803 non-null object
art                     4803 non-null object
production              4803 non-null object
visual_effects          4803 non-null object
costume                 4803 non-null object
camera                  4803 non-null object
lighting                4803 non-null object
writing                 4803 non-null object
crew_member             4803 non-null object
genres_bin              4803 non-null object
cast_bin                4803 non-null object
director_bin            4803 non-null object
dtypes: float64(3), int64(4), object(29)
memory usage: 1.3+ MB

In [305]:
movies1 = movies.drop(['homepage','spoken_languages','status'],axis=1,inplace=False)

In [333]:
movies1['category'] = 'Movie'

In [335]:
movies1.to_csv('movieNode_1206.csv',sep=',', header=True, index=False)

In [310]:
movies1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 33 columns):
category                4803 non-null object
budget                  4803 non-null int64
genres                  4803 non-null object
id                      4803 non-null int64
keywords                4803 non-null object
original_language       4803 non-null object
original_title          4803 non-null object
overview                4800 non-null object
popularity              4803 non-null float64
production_companies    4803 non-null object
production_countries    4803 non-null object
release_date            4802 non-null object
revenue                 4803 non-null int64
runtime                 4801 non-null float64
tagline                 3959 non-null object
title                   4803 non-null object
vote_average            4803 non-null float64
vote_count              4803 non-null int64
main_cast               4803 non-null object
director                4803 non-null object
editing                 4803 non-null object
sound                   4803 non-null object
art                     4803 non-null object
production              4803 non-null object
visual_effects          4803 non-null object
costume                 4803 non-null object
camera                  4803 non-null object
lighting                4803 non-null object
writing                 4803 non-null object
crew_member             4803 non-null object
genres_bin              4803 non-null object
cast_bin                4803 non-null object
director_bin            4803 non-null object
dtypes: float64(3), int64(4), object(26)
memory usage: 1.2+ MB

In [334]:
movies1.head(1)

,category,budget,genres,id,keywords,original_language,original_title,overview,popularity,production_companies,...,production,visual_effects,costume,camera,lighting,writing,crew_member,genres_bin,cast_bin,director_bin
0,Movie,237000000,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[culture clash, future, space war, space colon...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[289, 306, 444, 574]",...,"[1262, 2710, 6347, 8529, 20294, 1016177, 14017...","[6690, 113145, 93214, 957874, 1204668, 1206410...","[8527, 17675, 29067, 1071680, 1202850, 1310064...","[18265, 33302, 72201, 1177364, 1398970, 1401806]","[1401805, 1401807, 1453938]",[2710],"[42288, 58188, 89714, 122607, 236696, 956198, ...","[1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, ...","[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."